import './page-styles.css'
import { PageFrame, PageSection, Faq } from './pages.jsx'
import { CodeBlock } from './code.jsx'

export function AlembicAlternativePage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="alembic alternative" title={<>A Modern Alembic Alternative<br /><em>for SQLAlchemy.</em></>} intro={<>Looking for an Alembic alternative for SQLAlchemy? dbwarden is a declarative database migration tool where your SQLAlchemy models remain the source of truth and migrations are derived from schema changes. What reaches the pull request is plain SQL: reviewable by any DBA, executable without the Python runtime, and checked against the database before it ships.</>}>
    <PageSection number="01" label="The difference" title="Models are the schema. SQL is derived." doc="https://docs.dbwarden.org/features/">
      <div className="why-split"><div><p>Alembic keeps schema truth in a chain of revision scripts. Each revision describes the transition from one version to the next, and over time the chain becomes the effective definition of the schema. dbwarden keeps the schema in the SQLAlchemy models your application already imports, and derives plain SQL migrations from that one source of truth.</p><p>The generated SQL is committed, reviewed, and deployed, but it is output, not a second schema to maintain. Old migrations stay useful for review and deployment, but they no longer define the database.</p><p>This matters because most SQLAlchemy migration workflows describe the schema twice: once in the models, once in the migration scripts, and nothing checks the two stay in agreement. The disagreement usually turns up in production, at the moment the database is asked to change.</p></div><div><span className="comparison-label muted">Alembic revision</span><CodeBlock label="revision.py">{`revision = "ae1027a6acf"\ndown_revision = "1975ea83b712"\n\ndef upgrade():\n    op.add_column("users", sa.Column("bio", sa.Text()))\n\ndef downgrade():\n    op.drop_column("users", "bio")`}</CodeBlock><span className="comparison-label">dbwarden model + artifact</span><CodeBlock label="models.py">{`class User(Base):\n    bio = Column(Text, nullable=True)\n\n-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;`}</CodeBlock></div></div>
    </PageSection>
    <PageSection number="02" label="The workflows" title="The same schema change, two workflows." doc="https://docs.dbwarden.org/features/">
      <div className="why-split"><div><p>Both workflows are short. The difference shows up over time: Alembic keeps authorship and judgment in every revision forever, while dbwarden makes generation and SQL review the recurring responsibility.</p></div><div><span className="comparison-label muted">Alembic</span><CodeBlock label="terminal">{`# edit models.py\n$ alembic revision --autogenerate "add bio"\n  # review revision script\n  # write/verify downgrade()\n  # commit revision + model\n$ alembic upgrade head`}</CodeBlock><span className="comparison-label">dbwarden</span><CodeBlock label="terminal">{`# edit models.py\n$ dbwarden make-migrations "add bio"\n  # review generated SQL\n  # commit model + migration SQL\n$ dbwarden migrate`}</CodeBlock></div></div>
    </PageSection>
    <PageSection number="03" label="Side by side" title="What changes when you switch." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/">
      <section className="comparison-table-section"><div className="section-label">/ at a glance</div><table><thead><tr><th>Capability</th><th>Alembic</th><th>dbwarden</th></tr></thead><tbody><tr><th>SQLAlchemy integration</th><td>Yes</td><td>Yes</td></tr><tr><th>Model-driven generation</th><td>Autogenerate from live DB</td><td>Diff from models or committed state</td></tr><tr><th>Models as schema authority</th><td>No: revision chain is authoritative</td><td>Yes: models define the schema</td></tr><tr><th>Generated artifact</th><td>Python revision script</td><td>Plain SQL with upgrade + rollback</td></tr><tr><th>Generated rollback</th><td>Manual downgrade function</td><td>Generated contract, placeholder refused</td></tr><tr><th>Safety analysis</th><td>None built-in</td><td>INFO / WARNING / ERROR classifier</td></tr><tr><th>Impact analysis</th><td>None built-in</td><td>AST + grep scan of application code</td></tr><tr><th>Schema state</th><td>Revision-based (version table)</td><td>Checksummed snapshots + model state</td></tr><tr><th>Schema drift detection</th><td>Implicit via autogenerate</td><td>Deterministic diff from snapshots or live DB</td></tr><tr><th>Offline generation</th><td>Offline SQL rendering</td><td>Committed model state, no DB needed</td></tr><tr><th>Migration correctness verification</th><td>None built-in</td><td>Convergence gate + round-trip verification</td></tr><tr><th>FastAPI integration</th><td>Ecosystem (third-party)</td><td>Official plugin with sessions + health</td></tr><tr><th>Repeatable migrations</th><td>Not built-in</td><td>Runs-always (RA__) + runs-on-change (ROC__)</td></tr><tr><th>Seed management</th><td>Not built-in</td><td>Code seeds + file seeds with rollback</td></tr><tr><th>Rename detection</th><td>Drop + create (reviewer must catch)</td><td>Explicit --rename flag, never guesses</td></tr><tr><th>Multi-database</th><td>Separate env.py per database</td><td>Unified config with per-database isolation</td></tr></tbody></table></section>
    </PageSection>
    <PageSection number="04" label="Migration path" title="Six steps, none destructive." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/">
      <div className="why-split"><div><p>Migrating from Alembic is a non-destructive, six-step process. Your models stay exactly where they are and your database is never rebuilt; you are replacing the migration workflow, not the schema.</p><ul><li><strong>Install and configure.</strong> <code className="inline-code">uv add dbwarden</code>, create <code className="inline-code">dbwarden.py</code>. This replaces alembic.ini and env.py.</li><li><strong>Generate the baseline.</strong> <code className="inline-code">make-migrations "baseline from alembic"</code> emits the full schema from your models.</li><li><strong>Baseline the database.</strong> <code className="inline-code">migrate --baseline</code> records the migration as applied without running it.</li><li><strong>Verify convergence.</strong> <code className="inline-code">status</code>, <code className="inline-code">check</code>, and <code className="inline-code">diff</code> must all be clean.</li><li><strong>Offline CI (optional).</strong> <code className="inline-code">export-models</code>, commit the state file, and generate offline in CI.</li><li><strong>Retire Alembic.</strong> Remove alembic.ini, env.py, and versions/ from the active workflow.</li></ul><a className="text-link" href="/migrate-from-alembic">Read the full migration guide <span>↗</span></a></div><div><span className="comparison-label">the sequence</span><CodeBlock label="terminal">{`$ dbwarden init\n$ dbwarden make-migrations "baseline from alembic"\n$ dbwarden migrate --baseline\n$ dbwarden status\n$ dbwarden diff`}</CodeBlock></div></div>
    </PageSection>
    <Faq items={[
      { q: 'Is dbwarden a drop-in replacement for Alembic?', a: 'Not exactly. dbwarden is a different approach: models as the schema authority, plain SQL as the artifact, generated rollback alongside upgrade. The migration workflow changes, but your models stay where they are.' },
      { q: 'What happens to the existing Alembic history?', a: 'It stays in git, which is where old revisions belong. `make-migrations "baseline from alembic"` emits the full current schema from your models, and `migrate --baseline` records it as applied without running any DDL.' },
      { q: 'Can dbwarden and Alembic run side by side?', a: 'Yes. They track state in separate tables, so both tools can coexist during a transition period. Generate the same change with both and compare the SQL until you are confident.' },
      { q: 'When should I stay with Alembic?', a: 'When Python data migrations are central to your workflow, you rely on branching and merging revision graphs, or you want imperative control over every migration step.' },
      { q: 'What is the main advantage of switching?', a: 'Models remain the single source of truth. Generated SQL is reviewable by anyone, rollback is a contract rather than a convention, and the database is verified against the models rather than trusted from a version table.' },
    ]} />
    <section className="fit-section"><div className="section-label">/ honest fit</div><div className="fit-grid"><div><strong>Choose dbwarden when</strong><p>You want SQLAlchemy models as the single source of truth, plain SQL reviewable by any DBA, and rollback as a generated contract rather than a manual promise. Safety classification, impact analysis, and correctness verification come with the workflow, and PostgreSQL, MySQL, or ClickHouse share one Python workflow.</p></div><div><strong>Choose something else when</strong><p>Python data migrations are central to your workflow, you rely on branching and merging revision graphs, or you want imperative control over every migration step, including arbitrary Python inside upgrade and downgrade. Teams with deep Alembic expertise and mostly data-transformation workloads can stay with what they know.</p></div></div></section>
    <section className="article-links"><div className="section-label">/ keep reading</div><div><a href="/compare/alembic">dbwarden vs Alembic <span>↗</span></a><a href="/migrate-from-alembic">Migrate from Alembic <span>↗</span></a><a href="https://docs.dbwarden.org/getting-started/setup/" target="_blank" rel="noreferrer">Get started with dbwarden <span>↗</span></a><a href="/correctness">Correctness and verification <span>↗</span></a><a href="/fastapi">FastAPI migrations <span>↗</span></a></div></section>
  </PageFrame>
}