import './page-styles.css'
import { PageFrame } from './pages.jsx'
import { highlightBlock, renderCodeParts } from './code.jsx'
import { cloneElement, isValidElement } from 'react'

const comparisons = [
  { name: 'vs Alembic', description: 'The established imperative migration tool for SQLAlchemy. Revision scripts versus derived SQL.', href: '/compare/alembic' },
  { name: 'vs Atlas', description: 'A language-agnostic declarative schema platform with HCL, SQL, and ORM inputs.', href: '/compare/atlas' },
  { name: 'vs Django migrations', description: 'The model-driven workflow that inspired dbwarden, for non-Django SQLAlchemy stacks.', href: '/compare/django-migrations' },
]

export function ComparePage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare" title={<>Why dbwarden,<br /><em>and where it fits.</em></>} intro="Migration tools make different bets about where schema truth lives, what gets reviewed, and when risk becomes visible. These pages compare those bets directly, with code and the honest parts.">
    <section className="comparison-example-section"><div className="section-label">/ the short answers</div><div className="essay-body">
      <p><strong>Is dbwarden an alternative to SQLAlchemy?</strong> No: SQLAlchemy is the ORM, and dbwarden works with it. The thing being replaced is the migration layer. For SQLAlchemy projects that layer is usually Alembic, and dbwarden is the alternative to Alembic.</p>
      <p><strong>Which migration tool should I use?</strong> If you are on SQLAlchemy, the choice is between dbwarden and Alembic (Atlas is the language-agnostic option, Django migrations are for Django). dbwarden keeps the schema in the models and derives plain SQL with rollback beside it; Alembic keeps the schema in a chain of Python revision scripts.</p>
      <p><strong>Why dbwarden instead of Alembic?</strong> The migrations are derived from the models instead of hand-authored, the artifact is SQL that anyone can review and any database tool can run, rollback is generated as a contract rather than a convention, and the database is verified against the models rather than trusted from a version table.</p>
      <p>The pages below go into each comparison in detail, including where the other tool is the better choice.</p>
    </div></section>
    <section className="comparison-example-section"><div className="section-label">/ why dbwarden</div><div className="essay-body">
      <p>dbwarden keeps the schema in the SQLAlchemy models and derives the migrations from them. What reaches the pull request is plain SQL with upgrade and rollback in the same file, generated deterministically and checked against checksummed snapshots or live state before it ships. Because the models are the schema, review happens next to the application code that uses the schema, and old migration files are receipts rather than a second source of truth.</p>
      <p>The position has boundaries, and they matter for the comparisons. dbwarden is a SQLAlchemy tool: it does not manage schemas for other languages or frameworks, and it does not run arbitrary Python inside migration steps (manual migrations are SQL by design). Inside Django, the integrated migration system is the right tool; dbwarden targets the SQLAlchemy ecosystem around FastAPI, Flask, and plain SQLAlchemy services.</p>
      <p>The rest of this page goes into each comparison in detail, including where the other tool is the better choice.</p>
    </div></section>
    <section className="compare-list"><div className="section-label">/ the comparisons</div><div className="comparison-command-grid">{comparisons.map((comparison) => <div key={comparison.name}><span className="comparison-label">{comparison.name}</span><p>{comparison.description}</p><a className="text-link" href={comparison.href}>Read the comparison <span>↗</span></a></div>)}</div></section>
  </PageFrame>
}

export function AlembicComparisonPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare / alembic" title={<>dbwarden<br /><em>vs Alembic.</em></>} intro="Alembic keeps schema truth in a chain of revision scripts. dbwarden keeps it in the models and derives plain SQL. The difference is where authority, flexibility, and operational responsibility live.">
    <section className="comparison-table-section"><div className="section-label">/ at a glance</div><table><thead><tr><th>Concern</th><th>dbwarden</th><th>Alembic</th></tr></thead><tbody><tr><th>Source of truth</th><td>SQLAlchemy models</td><td>Revision chain</td></tr><tr><th>Artifact</th><td>Plain SQL</td><td>Python revision</td></tr><tr><th>Rollback</th><td>Generated contract</td><td>Author-defined downgrade</td></tr><tr><th>Offline generation</th><td>Committed model state</td><td>Offline SQL rendering</td></tr><tr><th>Runtime</th><td>SQL runner or any SQL system</td><td>Python and Alembic runtime</td></tr></tbody></table></section>
    <EssaySection number="01" title="The difference"><p>dbwarden is for SQLAlchemy teams that want models to remain the source of truth and migrations to become plain SQL receipts (reviewable by anyone, executable without the application runtime). Alembic is for teams that want an established imperative revision system, maximum Python-level control, and the broadest existing SQLAlchemy migration ecosystem. Neither is automatically better; they make different bets.</p><div className="comparison-code-grid"><div><span className="comparison-label muted">Alembic revision</span><ComparisonCode>{'revision = "ae1027a6acf"\ndown_revision = "1975ea83b712"\n\ndef upgrade():\n    op.add_column("users", sa.Column("bio", sa.Text()))\n\ndef downgrade():\n    op.drop_column("users", "bio")'}</ComparisonCode></div><div><span className="comparison-label">dbwarden model and artifact</span><ComparisonCode>{'class User(Base):\n    bio = Column(Text, nullable=True)\n\n-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;'}</ComparisonCode></div></div><p>The same change, twice: a Python program that must run inside Alembic, and a SQL file that any database tool can execute. Most of the differences below come from that one distinction.</p></EssaySection>
    <EssaySection number="02" title="Where truth lives"><p>SQLAlchemy models define what the schema should be. Generated migration files are artifacts of that state: useful for review and deployment, not a second schema to maintain. In Alembic, each revision describes the transition from one version to the next, and the chain becomes the effective definition of the schema. Models and the chain are two representations, and keeping them aligned is the team's responsibility.</p></EssaySection>
    <EssaySection number="03" title="What gets reviewed"><p>The file in the pull request contains the SQL that will run, with upgrade and rollback sections together. A DBA or any SQL-capable deployment system can execute it. Alembic's revision contains upgrade and downgrade functions. You can inspect rendered SQL, but the artifact itself is Python executed through Alembic's runtime.</p></EssaySection>
    <EssaySection number="04" title="Rollback and when risk appears"><p>Executable rollback is generated with the upgrade. Placeholder rollback is refused by default, and irreversible changes must be declared explicitly and visibly. In Alembic, every revision can define a downgrade, but whether it exists, works, and stays correct is left to the author and the review process.</p><p>Risk shows up at different points. dbwarden's snapshots make diffs deterministic, explicit rename flags prevent ambiguous drop-and-create behavior, and impact analysis can inspect application references before destructive changes ship. Alembic's autogenerate is useful, but the generated revision is still a candidate Python file that must be checked and corrected by the team.</p></EssaySection>
    <EssaySection number="05" title="The workflow"><p>A normal change in Alembic: edit the model, autogenerate a revision, inspect and possibly edit the upgrade, write or verify the downgrade, then commit two authoritative representations. In dbwarden: edit the model, generate a SQL artifact, read upgrade and rollback together, and commit the model plus its derived receipt. Both workflows are short. The difference shows up over time: Alembic keeps authorship and judgment in every revision forever, while dbwarden makes generation and SQL review the recurring responsibility.</p><p>Setup differs too. <code>alembic init</code> creates alembic.ini, env.py, a versions directory, and a script template. dbwarden uses one project-root declaration; model discovery is automatic, and <code>model_paths</code> can constrain it.</p><ComparisonCode>{'from dbwarden import DbwardenDatabase\n\nclass Primary(DbwardenDatabase):\n    database_name = "primary"\n    default = True\n    database_type = "postgresql"\n    database_url_sync = "postgresql://user:password@localhost:5432/primary"\n    model_paths = ["app"]'}</ComparisonCode><p>Generation is where the declarative model pays off. Alembic's autogenerate depends on a live database, and documented limits include renames and some constraint changes; a rename can become a drop and create unless a reviewer catches it. dbwarden uses checksummed snapshots for deterministic diffs, refuses to guess ambiguous renames, and supports a safe multi-step type-change workflow.</p><ComparisonCode>{'dbwarden make-migrations "rename name to full_name" \\\n  --rename users.name:full_name\n\n# preview without writing\ndbwarden make-migrations "add bio" --plan --sql'}</ComparisonCode></EssaySection>
    <EssaySection number="06" title="Applying and tracking"><p>Alembic runs Python revision programs through <code>alembic upgrade head</code>, with targets, relative steps, and <code>stamp</code> for an existing database. That is a complete system, but the target needs the project runtime and env.py. dbwarden reads pending SQL files and applies them in order; <code>--baseline</code> is the stamp equivalent, and <code>history</code>, <code>status</code>, <code>--count</code>, <code>--to-version</code>, and <code>--all</code> cover the operational workflow. Versioned SQL can also be handed directly to psql or a DBA.</p><ComparisonCode>{'dbwarden migrate\ndbwarden migrate --count 2\ndbwarden migrate --to-version 0007\ndbwarden migrate --baseline --to-version 0005\ndbwarden migrate --all'}</ComparisonCode><p>Execution has guardrails: migration locks prevent concurrent runners, <code>--dry-run</code> previews work, <code>--with-backup</code> captures a pre-migration state, and <code>--sandbox</code> replays changes before production.</p></EssaySection>
    <EssaySection number="07" title="Runtime, drift, and offline"><p>Alembic revisions are programs. Applying them requires the target environment to have Python, the project dependencies, the migration package, and a working env.py configuration. That flexibility is valuable when a migration needs arbitrary Python or data transformations. dbwarden migrations are SQL artifacts: <code>dbwarden migrate</code> is a convenient runner, not the definition of the deployment environment.</p><p>Alembic's version table records which revisions ran, not the complete structural state of the database. dbwarden compares models against live state on generation and also supports checksummed snapshots and exported model state, which makes offline generation possible: export once, commit the state file, and generate in CI with no database service.</p><ComparisonCode>{'dbwarden export-models --database primary\ngit add .dbwarden/model_state.primary.json\ndbwarden make-migrations "add bio column" --offline\ndbwarden check-impact\ndbwarden migrate --sandbox'}</ComparisonCode></EssaySection>
    <EssaySection number="08" title="Where Alembic fits better"><p>Alembic is the better call for Python data migrations, arbitrary application logic inside revisions, branching and merging revision graphs, older Python or SQLAlchemy environments, and teams that want manual control over every migration step (dbwarden's manual files are SQL by design). For a practical tiebreaker, inspect the last ten migrations: mostly pure schema changes suggest declarative tooling will remove recurring work; Python backfills and application-level transformations are imperative by nature, and Alembic is built for them.</p><p>Limits are part of the contract on both sides. Rollback protects schema shape, not deleted data. Enum additions, some partition changes, and unsupported operations may require an explicit irreversible marker or a manual migration. MySQL DDL is non-transactional and MariaDB does not provide full round-trip introspection. A warning is a review boundary, not a guarantee that a change is safe.</p><a className="text-link" href="/migrate-from-alembic">Switch from Alembic, step by step <span>↗</span></a><a className="text-link" href="https://docs.dbwarden.org/getting-started/migrating-from-alembic/" target="_blank" rel="noreferrer">Read the migration guide <span>↗</span></a></EssaySection>
  </PageFrame>
}

export function AtlasComparisonPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare / atlas" title={<>dbwarden<br /><em>vs Atlas.</em></>} intro="Both tools are declarative. The difference is where the schema lives, what gets applied, and how deeply the tool enters the application ecosystem.">
    <section className="comparison-table-section"><div className="section-label">/ at a glance</div><table><thead><tr><th>Concern</th><th>dbwarden</th><th>Atlas</th></tr></thead><tbody><tr><th>Schema source</th><td>SQLAlchemy models</td><td>HCL, SQL, or ORM providers</td></tr><tr><th>Artifact</th><td>Versioned SQL with rollback</td><td>Versioned SQL, or none in declarative apply</td></tr><tr><th>Apply modes</th><td>Versioned only</td><td>Declarative and versioned</td></tr><tr><th>Runtime</th><td>Python package in the app environment</td><td>Static Go binary</td></tr><tr><th>Ecosystem</th><td>SQLAlchemy-native, MIT</td><td>Language-neutral platform, commercial tiers</td></tr></tbody></table></section>
    <EssaySection number="01" title="The difference"><p>Atlas and dbwarden agree on the important philosophical split: describe the desired state and derive changes instead of hand-authoring every transition. Once that agreement is made, the difference becomes specific. Atlas is intentionally neutral about the application language: its schema can live in HCL, SQL, or an ORM provider, and the workflow remains Atlas's own. dbwarden makes the opposite choice: SQLAlchemy is not an input dialect at the edge of the system, it is the native substrate.</p><div className="comparison-code-grid"><div><span className="comparison-label muted">Atlas HCL</span><ComparisonCode>{'table "users" {\n  schema = schema.public\n  column "id" {\n    type = int\n  }\n  column "email" {\n    type = varchar(255)\n    null = false\n  }\n  primary_key {\n    columns = [column.id]\n  }\n  index "idx_email" {\n    columns = [column.email]\n    unique  = true\n  }\n}'}</ComparisonCode></div><div><span className="comparison-label">dbwarden model and artifact</span><ComparisonCode>{'class User(Base):\n    __tablename__ = "users"\n    email = Column(String(255), unique=True, nullable=False)\n    bio = Column(Text, nullable=True)\n\n-- upgrade\nCREATE TABLE IF NOT EXISTS users (\n    id INTEGER PRIMARY KEY,\n    email VARCHAR(255) NOT NULL UNIQUE,\n    bio TEXT\n);\n\n-- rollback\nDROP TABLE users;'}</ComparisonCode></div></div></EssaySection>
    <EssaySection number="02" title="Where the schema lives"><p>Atlas gives the desired state its own representation. HCL is explicit and independent, and SQL sources stay close to the database, a strength for polyglot teams and organizations that want schema ownership outside application repositories. The tradeoff for a SQLAlchemy project is another representation: models describe what the application imports, while HCL or SQL describes what the database follows. ORM providers reduce the duplication, but the metadata is still translated into Atlas's concepts.</p><p>dbwarden keeps the schema in the SQLAlchemy models, full stop. Typed Meta declarations extend those models for comments, advanced indexes, storage options, ClickHouse engines, and other backend details, so schema review happens in the same change as the application code using the schema. The trade is equally clear: this is a SQLAlchemy tool, not a neutral platform for every language.</p></EssaySection>
    <EssaySection number="03" title="What gets applied"><p>Atlas has two modes. Declarative apply inspects the live database, computes a plan, and applies it directly, valuable for ephemeral preview databases. Versioned mode generates SQL files and applies them in order. dbwarden has one mode by design: every production change becomes a versioned SQL file before it can touch the database, generated in a pull request, reviewed, tested in staging, and applied byte for byte. The runner is convenient, but the SQL can be handed to a DBA or another deployment system.</p><ComparisonCode>{'$ atlas schema apply\n$ atlas migrate diff add_bio\n$ atlas migrate apply\n\n$ dbwarden make-migrations "add bio"\n$ dbwarden migrate'}</ComparisonCode><p>Rollback differs in shape. dbwarden generates upgrade and executable rollback together; placeholder rollback is refused by default, and irreversible changes need a visible declaration. Atlas's migration linter has broad SQL analyzers for destructive changes, locks, and incompatibilities, and in declarative mode reversing toward an earlier desired state is conceptually direct.</p></EssaySection>
    <EssaySection number="04" title="Drift, CI, and the dev database"><p>Atlas offers schema diffing and a dev database concept for normalizing and validating schemas. That is powerful when you want the database engine's own opinion during planning, but it generally means a scratch database is part of the workflow. dbwarden records checksummed snapshots and exported model state; generation can happen offline with no database service, no seeded container, and no Docker socket. Drift is exposed as part of the next normal model comparison rather than an audit someone must remember to schedule.</p></EssaySection>
    <EssaySection number="05" title="Runtime and ecosystem"><p>Atlas is a static Go binary: easy to install, consistent in containers, and independent of any language runtime. dbwarden is a Python package in the same environment as the application (a Python 3.12+ requirement, but in exchange you get direct model imports, import-time Meta validation, AST impact analysis, and framework plugins). Atlas is a company-backed platform with cloud schema registries, deploy tracking, Terraform and Kubernetes integrations, and commercial support. dbwarden is MIT-licensed open source with a focused core and plugins; its backend reach includes PostgreSQL, MySQL, MariaDB, SQLite, and ClickHouse features such as MergeTree engines, projections, dictionaries, materialized views, and codecs.</p><ComparisonCode>{'PostgreSQL  -> full round-trip\nMySQL       -> full round-trip, non-transactional DDL\nClickHouse  -> engines, projections, views, codecs\nMariaDB     -> migration target, limited introspection\nSQLite      -> full round-trip + dev-mode translation'}</ComparisonCode></EssaySection>
    <EssaySection number="06" title="Where Atlas fits better"><p>Atlas fits when services are polyglot and need one schema platform, when the schema should be independent of application code, when declarative apply is valuable for ephemeral environments, or when commercial platform integrations are part of the requirement. dbwarden fits when the team is deeply invested in SQLAlchemy, production artifacts must be frozen readable SQL, application-aware impact analysis matters, and PostgreSQL and ClickHouse share one Python workflow.</p><p>Practical answers: is dbwarden "Atlas for Python"? No: Atlas is a schema platform with its own representation; dbwarden promotes SQLAlchemy models to authority and only produces versioned SQL. Can you migrate? Apply an HCL or SQL schema, run <code>generate-models</code>, create a baseline, and mark it applied; SQLAlchemy provider users can start from their existing models.</p><a className="text-link" href="https://docs.dbwarden.org/getting-started/setup/" target="_blank" rel="noreferrer">Start with dbwarden docs <span>↗</span></a></EssaySection>
  </PageFrame>
}

export function DjangoComparisonPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare / django migrations" title={<>dbwarden<br /><em>vs Django migrations.</em></>} intro="Django proved that models should drive migrations. dbwarden brings that expectation to SQLAlchemy stacks without requiring Django or replacing SQL with Python operations.">
    <section className="comparison-table-section"><div className="section-label">/ at a glance</div><table><thead><tr><th>Concern</th><th>Django</th><th>dbwarden</th></tr></thead><tbody><tr><th>Scope</th><td>Inside Django projects</td><td>Any SQLAlchemy stack</td></tr><tr><th>Schema source</th><td>Django models</td><td>SQLAlchemy models</td></tr><tr><th>Artifact</th><td>Python operation modules</td><td>Plain SQL with rollback</td></tr><tr><th>State comparison</th><td>Reconstructed from migration chain</td><td>Live database, snapshots, or exported state</td></tr><tr><th>Data migrations</th><td>RunPython with historical models</td><td>SQL only (manual files)</td></tr></tbody></table></section>
    <EssaySection number="01" title="The difference"><p>If you are building Django, use Django migrations. If you are building FastAPI or another SQLAlchemy service, dbwarden brings the model-driven workflow with plain SQL artifacts. The shape is the same: change a model, run makemigrations, inspect the generated migration, run migrate. dbwarden keeps that shape: change a SQLAlchemy model, run make-migrations, inspect the SQL, run migrate. That matters because many Python developers leave Django for FastAPI, Flask, Litestar, workers, or data services and find the model-driven workflow stayed behind.</p><div className="comparison-code-grid"><div><span className="comparison-label muted">Django migration</span><ComparisonCode>{'class Migration(migrations.Migration):\n    dependencies = [("accounts", "0003_user")]\n    operations = [\n        migrations.AddField(\n            model_name="user",\n            name="bio",\n            field=models.TextField(null=True),\n        ),\n    ]'}</ComparisonCode></div><div><span className="comparison-label">dbwarden migration</span><ComparisonCode>{'-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;'}</ComparisonCode></div></div></EssaySection>
    <EssaySection number="02" title="Different artifacts"><p>Django writes Python migration modules containing operation objects such as AddField and AlterField, and the framework translates them into backend SQL at execution time. RunPython is a genuine superpower for data migrations that need historical models. dbwarden writes the SQL itself. Upgrade and rollback sit in the same file, so the code review sees the exact statements that will execute. A DBA can run the file without Python, and the runner is optional rather than a deployment requirement.</p><p>Django's operation layer buys backend portability and Python data migrations. dbwarden's <code>final-SQL</code> artifact buys direct review: what you approve is what the database executes.</p></EssaySection>
    <EssaySection number="03" title="What gets compared"><p>Django reconstructs state from the migration chain, then compares current models against that in-memory state. It is elegant and lets makemigrations work without a database, but it assumes the database matches the chain: an out-of-band production change can remain invisible until a later operation fails. dbwarden compares models against actual database state, checksummed schema snapshots, or exported model state. The next generation run exposes unexpected changes: the tool assumes hotfixes happen, because that is what production does.</p><ComparisonCode>{'$ python manage.py makemigrations\n$ python manage.py migrate\n\n$ dbwarden make-migrations "add bio"\n$ dbwarden migrate --database primary'}</ComparisonCode></EssaySection>
    <EssaySection number="04" title="Rollback, renames, and coupling"><p>Django can ask interactively whether a disappeared field was renamed, and most operations know how to reverse themselves; RunPython needs an explicit reverse function. dbwarden makes renames explicit flags that work in CI and leave a trace, and generates rollback into the SQL file; a change that cannot be reversed must say so before it enters the repository.</p><p>Django migrations are integrated with Django's app registry, settings, test runner, admin, dependency graph, and ecosystem, which is why Django projects should use them. dbwarden requires SQLAlchemy and nothing else: FastAPI, Flask, Litestar, queue workers, scripts, and data pipelines can use it, and the official FastAPI plugin adds session dependencies and health routes while the core stays framework-independent.</p></EssaySection>
    <EssaySection number="05" title="Beyond the Django playbook"><p>dbwarden adds application-aware impact analysis, sandbox replay, offline state, safe type changes, and reverse engineering into SQLAlchemy models, and treats ClickHouse as a first-class backend alongside PostgreSQL, MySQL, MariaDB, and SQLite. Typed metadata is backend-aware: <code>PGTableMeta</code> covers partitioning, row-level security, fillfactor, and tablespaces; <code>MyTableMeta</code> covers engines, charsets, and row formats; <code>CHTableMeta</code> covers engine families, partitioning, ordering, TTLs, projections, materialized views, dictionaries, codecs, and skip indexes.</p><ComparisonCode>{'dbwarden check-db\ndbwarden recover-model-state\ndbwarden generate-models --base app.models.Base'}</ComparisonCode><p>Django has stronger integrated data migrations, app-scoped dependency graphs, and a mature test database experience. Those are real advantages. dbwarden is not trying to be Django outside Django; it is trying to make SQLAlchemy feel native in its own ecosystem.</p></EssaySection>
    <EssaySection number="06" title="State and adoption"><p>Django reconstructs schema state by replaying its migration chain in memory, which makes every migration file load-bearing forever; <code>squashmigrations</code> exists to manage that growing chain. dbwarden keeps the same discipline: the convergence gate replays the full migration history against an empty database, so the SQL files remain load-bearing even though the models and checksummed state hold the authority.</p><p>State is stored as checksummed snapshots in <code>.dbwarden/schemas/</code> and exported model state such as <code>.dbwarden/model_state.primary.json</code>. State files must be backed up and recovered carefully, since <code>recover-model-state</code> can only repair what a snapshot can express.</p><p>For an existing Django database, <code>generate-models --base</code> can create SQLAlchemy models, a baseline can mark the existing schema as adopted, and <code>recover-model-state</code> repairs missing or invalid offline state.</p><ComparisonCode>{'$ dbwarden generate-models --base app.models.Base\n$ dbwarden make-migrations "baseline existing schema"\n$ dbwarden migrate --baseline\n$ dbwarden seed apply'}</ComparisonCode></EssaySection>
    <EssaySection number="07" title="Where Django fits better"><p>Django projects should use Django migrations: they are integrated with the ORM, app registry, tests, admin, and ecosystem, and replacing them would be unnecessary complexity. RunPython with historical models, app-scoped migration dependencies, and the mature test database experience are real advantages. dbwarden targets the gap Django leaves: SQLAlchemy stacks outside Django, where final SQL and rollback should be visible together, multiple database engines share one workflow, and offline generation and application impact checks matter.</p><a className="text-link" href="https://docs.dbwarden.org/getting-started/setup/" target="_blank" rel="noreferrer">Start with dbwarden docs <span>↗</span></a></EssaySection>
  </PageFrame>
}

function EssaySection({ number, title, children }) {
  return <section className="comparison-block essay-section"><div className="section-label">/ {number} <span>{title}</span></div><div className="essay-body">{formatInlineCode(children)}</div></section>
}

function ComparisonCode({ children }) {
  const parts = highlightBlock(String(children))
  return <pre className="comparison-code"><code>{renderCodeParts(parts, 'cmp')}</code></pre>
}

function InlineCode({ children }) {
  return <code className="comparison-inline-code">{children}</code>
}

function formatInlineCode(node) {
  if (typeof node === 'string') {
    const parts = node.split(/(`[^`]+`)/g)
    return parts.map((part, index) => part.startsWith('`') && part.endsWith('`')
      ? <InlineCode key={index}>{part.slice(1, -1)}</InlineCode>
      : part)
  }
  if (Array.isArray(node)) return node.map(formatInlineCode)
  if (isValidElement(node) && node.type !== ComparisonCode) {
    return cloneElement(node, undefined, formatInlineCode(node.props.children))
  }
  return node
}
