import { PageFrame } from './pages.jsx'
import { cloneElement, isValidElement } from 'react'

const comparisons = [
  { name: 'Alembic', slug: '/compare/alembic', description: 'The established imperative migration tool for SQLAlchemy.', href: '/compare/alembic' },
  { name: 'Atlas', description: 'A language-agnostic declarative schema platform with HCL, SQL, and ORM inputs.', href: '/compare/atlas' },
  { name: 'Django migrations', description: 'The model-driven workflow that inspired dbwarden for non-Django SQLAlchemy stacks.', href: '/compare/django-migrations' },
]

export function ComparePage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare" title={<>Choose the tool<br /><em>that fits the team.</em></>} intro="Migration tools make different bets about where schema truth lives, what gets reviewed, and when risk becomes visible. Compare those bets directly.">
    <section className="compare-principle"><div className="section-label">/ the short version</div><div className="compare-principle-grid"><strong>dbwarden is for SQLAlchemy teams that want models as authority and plain SQL as the frozen artifact.</strong><p>That is not automatically better than every alternative. It is a deliberate fit. These comparisons explain the tradeoffs so you can choose without marketing fog.</p></div></section>
    <section className="compare-list"><div className="section-label">/ comparison index</div><div className="compare-cards">{comparisons.map((comparison, index) => <ComparisonCard comparison={comparison} index={index} key={comparison.name} />)}</div></section>
    <section className="compare-guidance"><div className="section-label">/ decide by constraint</div><div className="compare-guidance-grid"><div><strong>Choose dbwarden</strong><p>SQLAlchemy is your native ecosystem. You want generated SQL reviewed in pull requests, rollback beside upgrade, application-aware impact analysis, and offline generation from committed state.</p></div><div><strong>Keep looking</strong><p>You need a polyglot schema platform, Django's integrated migration graph, declarative apply for ephemeral environments, or a commercial platform team around the tool.</p></div></div></section>
  </PageFrame>
}

export function AlembicComparisonPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare / alembic" title={<>dbwarden<br /><em>vs Alembic.</em></>} intro="Two serious tools for SQLAlchemy. The difference is not quality. It is where each tool puts authority, flexibility, and operational responsibility.">
    <section className="comparison-verdict"><span>the verdict</span><strong>Use dbwarden when you want models to remain the source of truth and migrations to become plain SQL receipts.</strong><p>Use Alembic when you want an established imperative revision system, maximum Python-level control, or the broadest existing SQLAlchemy migration ecosystem.</p></section>
    <section className="comparison-example-section"><div className="section-label">/ source examples</div><div className="comparison-example-intro"><h2>The exact shapes being compared.</h2><p>These are the representative examples from the article: Alembic's setup and revision model, then dbwarden's configuration, model metadata, and generated SQL.</p></div><div className="comparison-code-stack"><div><span className="comparison-label muted">Alembic setup</span><ComparisonCode>{'alembic init\n\n# env.py\ntarget_metadata = Base.metadata\n\n# versions/ae1027a6acf_add_bio.py\nrevision = "ae1027a6acf"\ndown_revision = "1975ea83b712"'}</ComparisonCode></div><div><span className="comparison-label">dbwarden setup</span><ComparisonCode>{'from dbwarden import DbwardenDatabase\n\nclass Primary(DbwardenDatabase):\n    database_name = "primary"\n    default = True\n    database_type = "postgresql"\n    database_url_sync = "postgresql://user:password@localhost:5432/primary"\n    model_paths = ["app"]'}</ComparisonCode></div><div><span className="comparison-label">dbwarden model metadata</span><ComparisonCode>{'class User(Base):\n    __tablename__ = "users"\n    id = Column(Integer, primary_key=True)\n    email = Column(String(255), unique=True, nullable=False)\n    bio = Column(Text, nullable=True)\n\n    class Meta(TableMeta):\n        comment = "Core user accounts"\n        indexes = [\n            IndexSpec(name="ix_users_bio", columns=["bio"]),\n        ]'}</ComparisonCode></div><div><span className="comparison-label">generated SQL artifact</span><ComparisonCode>{'-- upgrade\nCREATE TABLE IF NOT EXISTS users (\n    id INTEGER PRIMARY KEY,\n    email VARCHAR(255) NOT NULL UNIQUE,\n    bio TEXT\n);\nCOMMENT ON TABLE users IS \'Core user accounts\';\nCREATE INDEX CONCURRENTLY IF NOT EXISTS ix_users_bio ON users (bio);\n\n-- rollback\nDROP TABLE users;'}</ComparisonCode></div></div></section>
    <ComparisonBlock number="01" title="Where truth lives"><div className="comparison-columns"><div><span className="comparison-label">dbwarden</span><h2>Desired state in models.</h2><p>SQLAlchemy models define what the schema should be. Generated migration files are artifacts of that state, useful for review and deployment but not a second schema to maintain.</p></div><div><span className="comparison-label muted">Alembic</span><h2>Revision chain as authority.</h2><p>Each revision describes the transition from one version to the next. Models and the migration chain are two representations, and keeping them aligned is the team's responsibility.</p></div></div></ComparisonBlock>
    <ComparisonBlock number="02" title="What gets reviewed"><div className="comparison-columns"><div><span className="comparison-label">dbwarden</span><h2>Plain SQL.</h2><p>The file in the pull request contains the SQL that will run, with upgrade and rollback sections together. A DBA or any SQL-capable deployment system can execute it.</p></div><div><span className="comparison-label muted">Alembic</span><h2>Python operations.</h2><p>The revision contains upgrade and downgrade functions. You can inspect rendered SQL, but the artifact itself is Python executed through Alembic's runtime.</p></div></div></ComparisonBlock>
    <ComparisonBlock number="03" title="The escape hatch"><div className="comparison-columns"><div><span className="comparison-label">dbwarden</span><h2>Rollback as contract.</h2><p>Executable rollback is generated with the upgrade. Placeholder rollback is refused by default. Irreversible changes must be declared explicitly and visibly.</p></div><div><span className="comparison-label muted">Alembic</span><h2>Downgrade as responsibility.</h2><p>Every revision can define downgrade, but whether it exists, works, and remains correct is left to the author and the review process.</p></div></div></ComparisonBlock>
    <ComparisonBlock number="04" title="When risk appears"><div className="comparison-columns"><div><span className="comparison-label">dbwarden</span><h2>At generation time.</h2><p>Snapshots make diffs deterministic. Explicit rename flags prevent ambiguous drop-and-create behavior. Impact analysis can inspect application references before destructive changes ship.</p></div><div><span className="comparison-label muted">Alembic</span><h2>At revision review.</h2><p>Autogenerate is useful, but the generated revision is still a candidate Python file that must be checked and corrected by the team.</p></div></div></ComparisonBlock>
    <EssaySection number="05" title="The runtime boundary"><p>Alembic revisions are programs. Applying them requires the target environment to have Python, the project dependencies, the migration package, and a working env.py configuration. That flexibility is valuable when a migration needs arbitrary Python or data transformations.</p><p>dbwarden migrations are SQL artifacts. dbwarden migrate is a convenient runner, not the definition of the deployment environment. A DBA can take the file, a pipeline can pipe it to the database, and a minimal target does not need the application's Python runtime.</p></EssaySection>
    <EssaySection number="06" title="Drift and offline generation"><p>Alembic's version table records which revisions ran, not the complete structural state of the database. If a production hotfix changes the schema outside the chain, the next revision may be the first time the disagreement becomes visible.</p><p>dbwarden compares models against live state on generation and also supports checksummed snapshots and exported model state. That makes offline generation possible without pretending the version table proves reality.</p></EssaySection>
    <EssaySection number="07" title="A normal change"><p>In Alembic, you edit the model, autogenerate a revision, inspect and possibly edit upgrade, write or verify downgrade, then commit two authoritative representations. In dbwarden, you edit the model, generate a SQL artifact, read upgrade and rollback together, and commit the model plus its derived receipt.</p><p>Both workflows are short. The difference compounds over time: Alembic keeps authorship and judgment in every revision forever, while dbwarden makes generation and SQL review the recurring responsibility.</p></EssaySection>
    <EssaySection number="08" title="The same change in code"><div className="comparison-code-grid"><div><span className="comparison-label">Alembic revision</span><ComparisonCode>{'revision = "ae1027a6acf"\ndown_revision = "1975ea83b712"\n\ndef upgrade():\n    op.add_column("users", sa.Column("bio", sa.Text()))\n\ndef downgrade():\n    op.drop_column("users", "bio")'}</ComparisonCode></div><div><span className="comparison-label">dbwarden model and artifact</span><ComparisonCode>{'class User(Base):\n    bio = Column(Text, nullable=True)\n\n-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;'}</ComparisonCode></div></div></EssaySection>
    <EssaySection number="09" title="Setup is a different amount of code"><p>Alembic's <code>alembic init</code> creates `alembic.ini`, `env.py`, a versions directory, and a script template. That flexibility is useful for exotic setups, but most projects own a copied env.py whose important job is wiring `target_metadata`.</p><p>dbwarden uses one project-root declaration. Model discovery is automatic, `model_paths` can constrain it, and each configured database is selected with `--database`.</p><ComparisonCode>{'from dbwarden import DbwardenDatabase\n\nclass Primary(DbwardenDatabase):\n    database_name = "primary"\n    default = True\n    database_type = "postgresql"\n    database_url_sync = "postgresql://user:password@localhost:5432/primary"\n    model_paths = ["app"]'}</ComparisonCode></EssaySection>
    <EssaySection number="10" title="Generation, not just autogenerate"><p>Alembic's autogenerate is useful, but the generated revision remains a Python file the team owns. It still depends on a live database, and documented limits include renames and some constraint changes. A rename can become a drop and create unless a reviewer catches it.</p><p>dbwarden uses checksummed snapshots for deterministic diffs, refuses to guess ambiguous renames, and supports a safe multi-step type-change workflow. Intent is explicit and inspectable before the artifact is written.</p><ComparisonCode>{'dbwarden make-migrations "rename name to full_name" \\\n  --rename users.name:full_name\n\n# preview without writing\ndbwarden make-migrations "add bio" --plan --sql'}</ComparisonCode></EssaySection>
    <EssaySection number="11" title="Applying and tracking"><p>Alembic runs Python revision programs through `alembic upgrade head`, with targets, relative steps, and `stamp` for an existing database. That is a complete and flexible system, but the target needs the project runtime and env.py.</p><p>dbwarden reads pending SQL files and applies them in order. `--baseline` is the stamp equivalent, and `history`, `status`, `--count`, `--to-version`, and `--all` cover the operational workflow. Versioned SQL can also be handed directly to psql or a DBA.</p><ComparisonCode>{'dbwarden migrate\ndbwarden migrate --count 2\ndbwarden migrate --to-version 0007\ndbwarden migrate --baseline --to-version 0005\ndbwarden migrate --all'}</ComparisonCode></EssaySection>
    <EssaySection number="12" title="Offline CI and capabilities beyond parity"><p>Alembic can render pending SQL offline, but autogenerate still needs a live comparison database. dbwarden can export model state once and generate against committed state with no database service in CI.</p><p>The model-native approach also enables application-aware impact analysis, sandbox replay, multi-database workflows including ClickHouse, SQLite dev mode, reverse engineering with `generate-models`, and plugins for seeds, FastAPI, sandboxes, RBAC, and custom types. Versioned migrations are joined by `runs_always` files for grants and `runs_on_change` files for idempotent maintenance SQL.</p><ComparisonCode>{'dbwarden export-models --database primary\ngit add .dbwarden/model_state.primary.json\ndbwarden make-migrations "add bio column" --offline\n\ndbwarden check-impact\ndbwarden migrate --sandbox'}</ComparisonCode></EssaySection>
    <EssaySection number="13" title="Where Alembic fits better"><p>Alembic is the better call for Python data migrations, arbitrary application logic inside revisions, branching and merging revision graphs, older Python or SQLAlchemy environments, and teams that want manual control over every migration step. dbwarden's manual files are SQL by design.</p><p>For a practical tiebreaker, inspect the last ten migrations. Mostly pure schema changes suggest declarative tooling will remove recurring work. Python backfills and application-level transformations are genuinely imperative, and Alembic is built for them.</p></EssaySection>
    <section className="comparison-table-section"><div className="section-label">/ at a glance</div><table><thead><tr><th>Concern</th><th>dbwarden</th><th>Alembic</th></tr></thead><tbody><tr><th>Source of truth</th><td>SQLAlchemy models</td><td>Revision chain</td></tr><tr><th>Artifact</th><td>Plain SQL</td><td>Python revision</td></tr><tr><th>Rollback</th><td>Generated contract</td><td>Author-defined downgrade</td></tr><tr><th>Offline generation</th><td>Committed model state</td><td>Offline SQL rendering</td></tr><tr><th>Runtime</th><td>SQL runner or any SQL system</td><td>Python and Alembic runtime</td></tr></tbody></table></section>
    <section className="comparison-honesty"><strong>Where Alembic is the better call</strong><p>You need arbitrary Python in migration steps, deep custom revision control, or an existing organization built around Alembic conventions. Alembic is mature, respected, and often exactly right.</p><a className="text-link" href="https://docs.dbwarden.org/getting-started/migrating-from-alembic/" target="_blank" rel="noreferrer">Read the migration guide <span>↗</span></a></section>
  </PageFrame>
}

export function AtlasComparisonPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare / atlas" title={<>dbwarden<br /><em>vs Atlas.</em></>} intro="Both tools are declarative. The real difference is where the schema lives, what gets applied, and how deeply the tool enters the application ecosystem.">
    <section className="comparison-verdict"><span>the verdict</span><strong>Choose dbwarden when SQLAlchemy models should be the native schema language and production changes should always become frozen SQL.</strong><p>Choose Atlas when you need a language-agnostic schema platform, a dedicated schema representation, declarative apply for ephemeral environments, or broader platform integrations.</p></section>
    <section className="comparison-example-section"><div className="section-label">/ source examples</div><div className="comparison-example-intro"><h2>Two declarative languages.</h2><p>Atlas keeps the desired schema in its own representation. dbwarden keeps it in the SQLAlchemy models the application already imports.</p></div><div className="comparison-code-stack"><div><span className="comparison-label muted">Atlas HCL</span><ComparisonCode>{'table "users" {\n  schema = schema.public\n  column "id" {\n    type = int\n  }\n  column "email" {\n    type = varchar(255)\n    null = false\n  }\n  primary_key {\n    columns = [column.id]\n  }\n  index "idx_email" {\n    columns = [column.email]\n    unique  = true\n  }\n}'}</ComparisonCode></div><div><span className="comparison-label">dbwarden model</span><ComparisonCode>{'class User(Base):\n    __tablename__ = "users"\n\n    id = Column(Integer, primary_key=True)\n    email = Column(String(255), unique=True, nullable=False)\n    bio = Column(Text, nullable=True)\n\n    class Meta(TableMeta):\n        comment = "Core user accounts"\n        indexes = [\n            IndexSpec(name="ix_users_bio", columns=["bio"]),\n        ]'}</ComparisonCode></div><div><span className="comparison-label">dbwarden generated artifact</span><ComparisonCode>{'-- upgrade\nCREATE TABLE IF NOT EXISTS users (\n    id INTEGER PRIMARY KEY,\n    email VARCHAR(255) NOT NULL UNIQUE,\n    bio TEXT\n);\nCOMMENT ON TABLE users IS \'Core user accounts\';\nCREATE INDEX CONCURRENTLY IF NOT EXISTS ix_users_bio ON users (bio);\n\n-- rollback\nDROP TABLE users;'}</ComparisonCode></div></div></section>
    <EssaySection number="01" title="Same philosophy. Different center."><p>Atlas and dbwarden agree on the important philosophical split: describe the desired state and derive changes instead of hand-authoring every transition. That puts both tools on the declarative side of schema management.</p><p>Once that agreement is made, the difference becomes more specific. Atlas is intentionally neutral about the application language. Its schema can live in HCL, SQL, or an ORM provider, and the workflow remains Atlas's own. dbwarden makes the opposite choice: SQLAlchemy is not an input dialect at the edge of the system. It is the native substrate.</p></EssaySection>
    <EssaySection number="02" title="Where the schema lives"><div className="comparison-prose-grid"><div><span className="comparison-label">Atlas</span><p>Atlas gives the desired state its own representation. HCL is explicit and independent; SQL sources stay close to the database. That separation is a strength for polyglot teams and organizations that want schema ownership outside application repositories.</p><p>The tradeoff for a SQLAlchemy project is another representation. Models describe what the application imports, while HCL or SQL describes what the database follows. ORM providers reduce the duplication, but the metadata is still translated into Atlas's concepts.</p></div><div><span className="comparison-label">dbwarden</span><p>The schema lives in the SQLAlchemy models, full stop. Typed Meta declarations extend those models for comments, advanced indexes, storage options, ClickHouse engines, and other backend details.</p><p>That depth means schema review happens in the same change as the application code using the schema. The trade is equally clear: this is a SQLAlchemy tool, not a neutral platform for every language.</p></div></div></EssaySection>
    <EssaySection number="03" title="The source looks different"><div className="comparison-code-grid"><div><span className="comparison-label">Atlas HCL</span><ComparisonCode>{'table "users" {\n  column "email" {\n    type = varchar(255)\n    null = false\n  }\n  index "idx_email" {\n    columns = [column.email]\n    unique = true\n  }\n}'}</ComparisonCode></div><div><span className="comparison-label">dbwarden SQLAlchemy</span><ComparisonCode>{'class User(Base):\n    __tablename__ = "users"\n    email = mapped_column(String(255),\n                          nullable=False,\n                          unique=True)'}</ComparisonCode></div></div><p>Atlas's representation is deliberately independent. dbwarden's representation is deliberately native to the application. Neither is universally correct; the choice is whether separation or integration is the more valuable property.</p></EssaySection>
    <EssaySection number="04" title="What gets applied"><p>Atlas has two useful modes. Declarative apply inspects the live database, computes a plan, and applies it directly. Versioned mode generates SQL files and applies them in order. The choice is valuable: ephemeral preview databases can use the direct mode, while production can freeze artifacts.</p><p>dbwarden has one mode by design. Every production change becomes a versioned SQL file before it can touch the database. It is generated in a pull request, reviewed, tested in staging, and applied byte for byte. The runner is convenient, but the SQL can be handed to a DBA or another deployment system.</p><ComparisonCode>{'$ atlas schema apply\n$ atlas migrate diff add_bio\n$ atlas migrate apply\n\n$ dbwarden make-migrations "add bio"\n$ dbwarden migrate'}</ComparisonCode></EssaySection>
    <EssaySection number="04" title="Rollback and safety"><div className="comparison-columns"><div><span className="comparison-label">dbwarden</span><h2>Contract first.</h2><p>Upgrade and executable rollback are generated together. Placeholder rollback is refused by default, and irreversible changes need a visible declaration. Explicit rename flags and safe type-change workflows keep ambiguous destructive operations from being silently invented.</p></div><div><span className="comparison-label muted">Atlas</span><h2>Plan and analyze.</h2><p>Atlas's migration linter has broad SQL analyzers for destructive changes, locks, and incompatibilities. In declarative mode, reversing toward an earlier desired state is conceptually direct. It is a strong choice when SQL-side lint coverage is the primary requirement.</p></div></div></EssaySection>
    <EssaySection number="05" title="Drift, CI, and the dev database"><p>Atlas offers schema diffing and a dev database concept for normalizing and validating schemas. That is powerful, especially when you want the database engine's own opinion during planning, but it generally means a scratch database is part of the workflow.</p><p>dbwarden records checksummed snapshots and exported model state. Generation can happen offline with no database service, no seeded container, and no Docker socket. Drift is exposed as part of the next normal model comparison rather than an audit someone must remember to schedule.</p></EssaySection>
    <EssaySection number="06" title="Where each fits best"><div className="comparison-fit-grid"><div><strong>dbwarden fits when</strong><ul><li>The team is deeply invested in SQLAlchemy.</li><li>Production artifacts must be frozen, readable SQL.</li><li>Application-aware impact analysis matters.</li><li>PostgreSQL and ClickHouse share one Python workflow.</li></ul></div><div><strong>Atlas fits when</strong><ul><li>Services are polyglot and need one schema platform.</li><li>The schema should be independent of application code.</li><li>Declarative apply is valuable for ephemeral environments.</li><li>Commercial platform integrations are part of the requirement.</li></ul></div></div></EssaySection>
    <EssaySection number="07" title="The runtime boundary"><p>Atlas is a static Go binary: easy to install, consistent in containers, and independent of any language runtime. That is part of its universality. dbwarden is a Python package in the same environment as the application, which costs a Python 3.12+ requirement but permits direct model imports, import-time Meta validation, AST impact analysis, and framework plugins.</p></EssaySection>
    <EssaySection number="08" title="Safety is not one problem"><p>Atlas has broader SQL-side linting for destructive changes, table locks, data-dependent failures, and backward incompatibilities. dbwarden combines a safety classifier with operational defaults such as PostgreSQL concurrent indexes, explicit renames, and `--safe-type-change`.</p><p>dbwarden's distinctive check is on the application side. `check-impact` can report routes and templates that still reference a column. SQL linting can say a drop is destructive; a project-aware tool can say what code it will break.</p><ComparisonCode>{'drop_column on users.username\n  References: 2\n    app/routes/users.py:34  attribute_access\n    app/templates/profile.jinja2:12  grep'}</ComparisonCode></EssaySection>
    <EssaySection number="09" title="Ecosystem and platform shape"><p>Atlas is a company-backed platform with cloud schema registries, deploy tracking, Terraform and Kubernetes integrations, and commercial support. Its open-core model puts some capabilities behind paid tiers. dbwarden is MIT-licensed open source with focused core and plugins. Its backend reach includes PostgreSQL, MySQL, MariaDB, SQLite, and ClickHouse features such as MergeTree engines, projections, dictionaries, materialized views, and codecs, with round-trip model generation.</p></EssaySection>
    <EssaySection number="10" title="Questions worth answering"><p><strong>Is dbwarden Atlas for Python?</strong> No. Atlas is a schema platform with its own representation and two apply modes. dbwarden promotes SQLAlchemy models to schema authority and only produces versioned SQL.</p><p><strong>Does the SQLAlchemy provider make dbwarden redundant?</strong> It can be enough if Atlas's translated provider workflow fits. dbwarden goes deeper with typed backend metadata, reverse engineering into models, and application-aware analysis.</p><p><strong>Can you migrate?</strong> Apply an HCL or SQL schema, run <InlineCode>dbwarden generate-models</InlineCode>, create a baseline, and mark it applied. SQLAlchemy provider users can start from their existing models.</p><p><strong>What about drift and rollback?</strong> Atlas can run <InlineCode>atlas schema diff</InlineCode> on demand, provides continuous cloud drift monitoring, and has <InlineCode>migrate down</InlineCode> in versioned mode. dbwarden detects drift in its normal generation loop and keeps rollback SQL beside upgrade.</p></EssaySection>
    <section className="comparison-honesty"><strong>Neither tool wins in the abstract.</strong><p>Atlas optimizes for universality and platform breadth. dbwarden optimizes for depth inside a SQLAlchemy project. Pick the constraint that is actually limiting your team.</p><a className="text-link" href="https://docs.dbwarden.org/getting-started/setup/" target="_blank" rel="noreferrer">Start with dbwarden docs <span>↗</span></a></section>
  </PageFrame>
}

export function DjangoComparisonPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="compare / django migrations" title={<>dbwarden<br /><em>vs Django migrations.</em></>} intro="Django proved that models should drive migrations. dbwarden brings that expectation to SQLAlchemy stacks without requiring Django or replacing SQL with Python operations.">
    <section className="comparison-verdict"><span>the verdict</span><strong>If you are building Django, use Django migrations. If you are building FastAPI or another SQLAlchemy service, dbwarden brings the model-driven workflow with plain SQL artifacts.</strong><p>The family resemblance is intentional. The guarantees and runtime boundaries are different.</p></section>
    <section className="comparison-example-section"><div className="section-label">/ source examples</div><div className="comparison-example-intro"><h2>The workflow Django made familiar.</h2><p>Django's model and operation file are translated into SQL at runtime. dbwarden gives SQLAlchemy the same generate-review-apply shape, with SQL and rollback visible in the repository.</p></div><div className="comparison-code-stack"><div><span className="comparison-label muted">Django model</span><ComparisonCode>{'from django.db import models\n\nclass User(models.Model):\n    email = models.EmailField(unique=True)\n    bio = models.TextField(blank=True, default="")\n\n    class Meta:\n        db_table = "users"'}</ComparisonCode></div><div><span className="comparison-label muted">Django operation file</span><ComparisonCode>{'class Migration(migrations.Migration):\n    dependencies = [("accounts", "0003_user_last_login")]\n\n    operations = [\n        migrations.AddField(\n            model_name="user",\n            name="bio",\n            field=models.TextField(blank=True, default=""),\n        ),\n    ]'}</ComparisonCode></div><div><span className="comparison-label">dbwarden SQLAlchemy model</span><ComparisonCode>{'class User(Base):\n    __tablename__ = "users"\n    email = Column(String(255), unique=True, nullable=False)\n    bio = Column(Text, nullable=True)\n\n    class Meta(TableMeta):\n        comment = "Core user accounts"'}</ComparisonCode></div><div><span className="comparison-label">dbwarden SQL artifact</span><ComparisonCode>{'-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;'}</ComparisonCode></div></div></section>
    <EssaySection number="01" title="The same daily shape"><p>Django's workflow is familiar: change a model, run makemigrations, inspect the generated migration, and run migrate. dbwarden uses the same memorable shape: change a SQLAlchemy model, run make-migrations, inspect the SQL, and run migrate.</p><p>The similarity matters because many Python developers leave Django for FastAPI, Flask, Litestar, workers, or data services and discover that the model-driven workflow stayed behind. dbwarden is built for that gap.</p></EssaySection>
    <EssaySection number="02" title="Different artifacts"><div className="comparison-prose-grid"><div><span className="comparison-label">Django</span><p>Django writes Python migration modules containing operation objects such as AddField and AlterField. The framework translates those operations into backend SQL at execution time. RunPython is a genuine superpower for data migrations that need historical models.</p></div><div><span className="comparison-label">dbwarden</span><p>dbwarden writes the SQL itself. Upgrade and rollback sit in the same file, so the code review sees the exact statements that will execute. A DBA can run the file without Python, and the runner is optional rather than a deployment requirement.</p></div></div></EssaySection>
    <EssaySection number="03" title="The artifacts in code"><div className="comparison-code-grid"><div><span className="comparison-label">Django migration</span><ComparisonCode>{'class Migration(migrations.Migration):\n    dependencies = [("accounts", "0003_user")]\n    operations = [\n        migrations.AddField(\n            model_name="user",\n            name="bio",\n            field=models.TextField(null=True),\n        ),\n    ]'}</ComparisonCode></div><div><span className="comparison-label">dbwarden migration</span><ComparisonCode>{'-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;'}</ComparisonCode></div></div><p>Django's operation layer buys backend portability and Python data migrations. dbwarden's final-SQL artifact buys direct review: what you approve is what the database executes.</p></EssaySection>
    <EssaySection number="04" title="What gets compared"><p>Django reconstructs state from the migration chain, then compares current models against that in-memory state. It is elegant and lets makemigrations work without a database. It also assumes the database matches the chain: an out-of-band production change can remain invisible until a later operation fails.</p><p>dbwarden compares models against actual database state, checksummed schema snapshots, or exported model state. The next generation run exposes unexpected changes. The tool assumes hotfixes happen because that is what production does.</p><ComparisonCode>{'$ python manage.py makemigrations\n$ python manage.py migrate\n\n$ dbwarden make-migrations "add bio"\n$ dbwarden migrate --database primary'}</ComparisonCode></EssaySection>
    <EssaySection number="04" title="Rollback, renames, and irreversibility"><div className="comparison-columns"><div><span className="comparison-label">Django</span><h2>Framework intelligence.</h2><p>Django can ask interactively whether a disappeared field was renamed, and most operations know how to reverse themselves. RunPython needs an explicit reverse function, and irreversible failures can surface when rollback is attempted.</p></div><div><span className="comparison-label muted">dbwarden</span><h2>Auditable intent.</h2><p>Renames are explicit flags that work in CI and leave a trace. Rollback is generated into the SQL file, and a change that cannot be reversed must say so before it enters the repository.</p></div></div></EssaySection>
    <EssaySection number="05" title="Coupling and scope"><p>Django migrations are integrated with Django's app registry, settings, test runner, admin, dependency graph, and third-party ecosystem. That integration is why Django projects should use them. Replacing them inside Django would be unnecessary self-inflicted complexity.</p><p>dbwarden requires SQLAlchemy and nothing else. FastAPI, Flask, Litestar, queue workers, scripts, and data pipelines can use it. The official FastAPI plugin adds session dependencies and health routes, while the core remains framework-independent.</p></EssaySection>
    <EssaySection number="06" title="Beyond the Django playbook"><p>dbwarden adds application-aware impact analysis, sandbox replay, offline state, safe type changes, and reverse engineering into SQLAlchemy models. It also treats ClickHouse as a first-class backend alongside PostgreSQL, MySQL, MariaDB, and SQLite.</p><p>Django has stronger integrated data migrations, app-scoped dependency graphs, and a mature test database experience. Those are real advantages. dbwarden is not trying to be Django outside Django; it is trying to make SQLAlchemy feel native in its own ecosystem.</p><p>The typed metadata surface is also broader than Django's generic model options: <InlineCode>PGTableMeta</InlineCode>, <InlineCode>MyTableMeta</InlineCode>, and <InlineCode>CHTableMeta</InlineCode> cover backend-specific storage, while column metadata and <InlineCode>IndexSpec</InlineCode> support partial, covering, ordered, and storage-parameterized indexes.</p><ComparisonCode>{'dbwarden check-db\ndbwarden recover-model-state\ndbwarden generate-models --base app.models.Base'}</ComparisonCode></EssaySection>
    <EssaySection number="07" title="Where each fits best"><div className="comparison-fit-grid"><div><strong>Use Django migrations when</strong><ul><li>The application is a Django project.</li><li>RunPython and historical models are central.</li><li>App-scoped migration dependencies matter.</li></ul></div><div><strong>Use dbwarden when</strong><ul><li>The application uses SQLAlchemy outside Django.</li><li>Final SQL and rollback must be visible together.</li><li>Multiple database engines share one workflow.</li><li>Offline generation and application impact checks matter.</li></ul></div></div></EssaySection>
    <EssaySection number="08" title="Renames and execution"><p>Django's interactive questioner asks whether a disappeared field was renamed and writes a <InlineCode>RenameField</InlineCode>. dbwarden makes the same intent explicit and automation-friendly:</p><ComparisonCode>{'dbwarden make-migrations "rename name" --rename users.name:full_name\ndbwarden make-migrations "rename orders" --rename-table order:orders'}</ComparisonCode><p>Django's <InlineCode>migrate</InlineCode>, <InlineCode>showmigrations</InlineCode>, <InlineCode>--fake</InlineCode>, and <InlineCode>--plan</InlineCode> form a mature app-aware toolkit. dbwarden mirrors the core workflow with <InlineCode>status</InlineCode>, <InlineCode>history</InlineCode>, <InlineCode>--baseline</InlineCode>, <InlineCode>--dry-run</InlineCode>, <InlineCode>--count</InlineCode>, <InlineCode>--to-version</InlineCode>, and <InlineCode>--all</InlineCode>. It also has <InlineCode>runs_always</InlineCode> and <InlineCode>runs_on_change</InlineCode> migration types for grants and maintenance SQL.</p></EssaySection>
    <EssaySection number="09" title="State: implicit chain versus explicit files"><p>Django reconstructs schema state by replaying its migration chain in memory. That makes generation database-free, but makes every migration file load-bearing forever. `squashmigrations` exists to manage that growing chain.</p><p>dbwarden stores checksummed snapshots in `.dbwarden/schemas/` and exported model state such as `.dbwarden/model_state.primary.json`. Old SQL receipts can be deleted because models and state hold the authority, but state files must be backed up and recovered carefully.</p></EssaySection>
    <EssaySection number="10" title="What dbwarden adds"><p>Impact analysis scans Python and templates before destructive changes. Sandbox replay, `--dry-run`, `--with-backup`, offline state, reverse engineering, and `--safe-type-change` make the workflow more operationally explicit. Official plugins cover Testcontainers sandboxes and seeds.</p><p>It also treats ClickHouse as a first-class backend, alongside PostgreSQL, MySQL, MariaDB, and SQLite, with backend-specific typed Meta classes and model round-tripping.</p></EssaySection>
    <EssaySection number="11" title="Questions worth answering"><p><strong>Can dbwarden replace Django migrations inside Django?</strong> No. Django's migrations are integrated with its ORM, app registry, tests, admin, and ecosystem. Use Django migrations for Django.</p><p><strong>Is it Django migrations for FastAPI?</strong> As an elevator pitch, yes: models, generate, review, apply. The actual artifacts are SQL, rollback is a contract, and the tool is SQLAlchemy-native.</p><p><strong>Can a Django app move to SQLAlchemy?</strong> Generate SQLAlchemy models from the existing database with <InlineCode>--base</InlineCode>, create a baseline, and mark it applied. The old <InlineCode>django_migrations</InlineCode> table becomes historical.</p><p><strong>Does dbwarden understand Django-style app structure?</strong> It uses model discovery, <InlineCode>model_paths</InlineCode>, and <InlineCode>model_tables</InlineCode> for explicit module and database ownership rather than Django apps.</p><p><strong>What about testing and seeds?</strong> Use sandbox replay and the Testcontainers plugin for real database validation; <InlineCode>dbwarden-seeds</InlineCode> supports code and file seeds with <InlineCode>dbwarden seed apply</InlineCode> and optional <InlineCode>auto_apply_seeds</InlineCode>.</p></EssaySection>
    <section className="comparison-honesty"><strong>Same genus, different species.</strong><p>Django normalized model-driven migrations. dbwarden carries that expectation into the broader SQLAlchemy ecosystem while changing the artifact, rollback contract, and backend reach.</p><a className="text-link" href="https://docs.dbwarden.org/getting-started/setup/" target="_blank" rel="noreferrer">Start with dbwarden docs <span>↗</span></a></section>
  </PageFrame>
}

function EssaySection({ number, title, children }) {
  return <section className="comparison-block essay-section"><div className="section-label">/ {number} <span>{title}</span></div><div className="essay-body">{formatInlineCode(children)}</div></section>
}

function ComparisonBlock({ number, title, children }) {
  return <section className="comparison-block"><div className="section-label">/ {number} <span>{title}</span></div>{children}</section>
}

function ComparisonCode({ children }) {
  return <pre className="comparison-code"><code>{children}</code></pre>
}

function InlineCode({ children }) {
  return <code className="comparison-inline-code">{children}</code>
}

function formatInlineCode(node) {
  if (typeof node === 'string') {
    const parts = node.split(/(`[^`]+`)/g)
    return parts.map((part, index) => part.startsWith('`') && part.endsWith('`')
      ? <InlineCode key={index}>{part.slice(1, -1)}</InlineCode>
      : part)
  }
  if (Array.isArray(node)) return node.map(formatInlineCode)
  if (isValidElement(node) && node.type !== ComparisonCode) {
    return cloneElement(node, undefined, formatInlineCode(node.props.children))
  }
  return node
}

function ComparisonCard({ comparison, index }) {
  const Tag = comparison.href ? 'a' : 'article'
  return <Tag className={comparison.href ? 'compare-card' : 'compare-card is-upcoming'} {...(comparison.href ? { href: comparison.href } : {})}><div><span>0{index + 1}</span><em /></div><h2>dbwarden<br /><strong>vs {comparison.name}</strong></h2><p>{comparison.description}</p>{comparison.href && <span className="compare-arrow">↗</span>}</Tag>
}
