import './page-styles.css'
import { PageFrame, PageSection } from './pages.jsx'
import { CodeBlock } from './code.jsx'

export function CorrectnessPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="correctness" title={<>Database Migration<br /><em>Correctness.</em></>} intro="Migration tools generate SQL. DBWarden also verifies that the generated migration actually converges the database to the model state and that rollback works. This is DBWarden's technical authority pillar.">
    <PageSection number="01" label="Deterministic diffs" title="Same inputs, same SQL, every time." doc="https://docs.dbwarden.org/correctness/deterministic-diff/"><p>After every migration, dbwarden writes a checksummed JSON snapshot of the schema to <code className="inline-code">.dbwarden/schemas/</code>. Generation diffs models against that snapshot or live state, so the same inputs produce the same SQL on every machine. Renames come out as renames, not as a drop plus a create.</p></PageSection>
    <PageSection number="02" label="Rollback contract" title="Rollback is classified before it ships." doc="https://docs.dbwarden.org/correctness/rollback-generation/"><p>Every generated migration carries upgrade and rollback sections, and dbwarden classifies the rollback before the file is accepted: real, conditional, irreversible, or placeholder. Placeholder rollback is refused by default. When a change cannot be reversed (an enum value addition, a lossy ClickHouse engine swap), the migration has to declare it explicitly.</p><CodeBlock>{`-- upgrade
ALTER TABLE users ADD COLUMN bio TEXT;

-- rollback
ALTER TABLE users DROP COLUMN bio;`}</CodeBlock><p>For the rare truly irreversible change:</p><CodeBlock>{`-- dbwarden: irreversible`}</CodeBlock></PageSection>
    <PageSection number="03" label="Convergence gate" title="Full history, replayed from scratch." doc="https://docs.dbwarden.org/correctness/convergence-gate/"><p>CI starts an empty database, applies every migration exactly as production would, extracts the resulting schema, and compares it with the models. Any drift fails the build.</p><CodeBlock>{`$ dbwarden migrate --database primary
$ dbwarden diff --database primary   # must report zero differences`}</CodeBlock><p>This catches what syntax checks miss: a migration that forgot the model's index, a column removed from the model but never dropped, a rename applied backwards, backend metadata missing from hand-written SQL. On long histories, <code className="inline-code">migrate --defer-snapshots</code> replays hundreds of migrations with a single final snapshot instead of one reflection per file.</p></PageSection>
    <PageSection number="04" label="Round-trip verification" title="Upgrade and rollback, exercised in sequence." doc="https://docs.dbwarden.org/correctness/round-trip-verification/"><p>A <a className="prose-link" href="https://harness.dbwarden.org/correctness/round-trips/" target="_blank" rel="noreferrer">test harness</a> applies a migration and its rollback in sequence and verifies the schema returns to its starting state. The rollback path actually runs, rather than existing only as generated text.</p></PageSection>
    <PageSection number="05" label="Offline integrity" title="Generate without a database. Verify against one." doc="https://docs.dbwarden.org/correctness/offline-integrity/"><p><code className="inline-code">export-models</code> commits a checksummed model state file; <code className="inline-code">make-migrations --offline</code> diffs against it with no database service in CI. Offline generation is deterministic, and the convergence gate on a live database proves the SQL actually applies.</p><CodeBlock>{`$ dbwarden export-models --database primary
$ dbwarden make-migrations "add bio" --offline`}</CodeBlock></PageSection>
    <section className="fit-section"><div className="section-label">/ honest limits</div><div className="fit-grid"><div><strong>What it verifies</strong><p>Schema shape, rollback executability, and that the full migration history reproduces the models.</p></div><div><strong>What it can't</strong><p>Business intent. An ERROR classification is a review boundary, not a guarantee; deleted data stays deleted.</p></div></div></section>
  </PageFrame>
}
