import './page-styles.css'
import { PageFrame, PageSection, Faq } from './pages.jsx'
import { CodeBlock } from './code.jsx'

export function GenerationPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="tool scope / generation" title={<>Generate SQL Migrations<br /><em>from SQLAlchemy Models.</em></>} intro="DBWarden takes a model-native approach to SQLAlchemy migration generation: models remain authoritative and generated SQL is the artifact. Alembic's autogenerate compares metadata against the database; DBWarden diffs models against committed state." install="uv add dbwarden">
    <PageSection number="01" label="The derived artifact" title="From model change to versioned SQL." doc="https://docs.dbwarden.org/features/">
      <div className="why-split"><div><p>Edit a SQLAlchemy model, run <code className="inline-code">make-migrations</code>, and the tool writes a versioned SQL file with upgrade and rollback sections beside each other. The file is what gets reviewed in the pull request and committed to source control; the plan that produced it is written alongside as <code className="inline-code">.plan.json</code>, machine-readable metadata for CI and debugging that <code className="inline-code">migrate</code> never executes.</p><p>Generation diffs the model state against the latest schema snapshot, falling back to the live database when no snapshot exists yet. The diff engine emits typed operations, and the SQL is derived from those operations, so the same models and the same state always produce the same SQL. Names are auto-derived from the change, or you pass a description like <code className="inline-code">"add bio"</code>.</p><p>The migration file is derived from the models. Old files stay useful for review and deployment, but they don't define the schema anymore; the next generation run exposes any disagreement.</p></div><div><span className="comparison-label">the model change</span><CodeBlock label="models.py">{`class User(Base):\n    __tablename__ = "users"\n    email = Column(String(255), unique=True, nullable=False)\n    bio = Column(Text, nullable=True)`}</CodeBlock><span className="comparison-label">the derived artifact</span><CodeBlock label="primary__0002_add_bio.sql">{`-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;`}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Where does make-migrations write the file?', a: 'To `migrations/<database_name>/`, named `{database_name}__{version}_{description}.sql`. Each database keeps its own linear versioned sequence.' },
        { q: 'How are renames detected?', a: 'When a column is dropped and a new column of the same type is added, dbwarden detects a potential rename and emits `ALTER TABLE ... RENAME COLUMN` instead of a drop-and-create. Ambiguous cases can be declared with `--rename`.' },
        { q: 'Can I preview the migration before writing it?', a: 'Yes: `make-migrations --plan` prints the migration plan JSON without writing any files.' },
      ]} />
    </PageSection>
    <PageSection number="02" label="Offline generation" title="Generate without a database running." doc="https://docs.dbwarden.org/correctness/offline-integrity/">
      <div className="why-split"><div><p><code className="inline-code">export-models</code> commits a checksummed model state file, and <code className="inline-code">make-migrations --offline</code> diffs against that state. CI can generate migrations with no database service, no seeded container, and no Docker socket, deterministically, on every machine.</p><p>The offline baseline replaces the database as the diff input, which removes the class of failures where a fresh database in CI produces different SQL than a long-lived one locally. Because the state file is checksummed and committed, generation is reproducible from git history: check out an old commit, and the same models and state produce the same migration.</p><p>Offline generation doesn't replace verification. The SQL still has to be applied to a real database to prove it works, which is what the convergence gate does. Offline is for speed and determinism in CI; the live check is for proof.</p></div><div><span className="comparison-label">export once, commit the state</span><CodeBlock>{'$ dbwarden export-models --database primary\n$ dbwarden make-migrations "add bio" --offline'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Does generation need a live database?', a: 'Not after the first `migrate`. `make-migrations` diffs against the latest schema snapshot in `.dbwarden/schemas/`; without a snapshot it falls back to the live database. `--offline` uses exported model state instead.' },
        { q: 'What does export-models commit?', a: 'A checksummed model state file representing the current models, committed to the repository. It replaces the database as the diff baseline, so CI needs no database service at all.' },
        { q: 'Is offline generation deterministic?', a: 'Yes. Generation diffs against committed state rather than a live database, so the same model state and snapshot produce the same SQL every run.' },
      ]} />
    </PageSection>
    <section className="comparison-example-section"><div className="section-label">/ why not just alembic autogenerate?</div><div className="essay-body">
      <p><strong>"Alembic already generates migrations from my SQLAlchemy models. Why do I need DBWarden?"</strong></p>
      <p>Alembic's autogenerate compares application metadata against the live database and produces a candidate Python revision. It is useful, but the comparison has known limits: renames can become drop-and-create unless the reviewer catches them, the generated revision is a Python file that must run inside Alembic's runtime, and there is no generated rollback — the downgrade function is the author's responsibility.</p>
      <p>DBWarden takes a different architectural bet. Models remain authoritative, and generated SQL is the artifact. The diff runs against checksummed snapshots or exported model state (not just the live database), renames are explicit flags that never silently become destructive, rollback is generated alongside upgrade as a contract, and the safety classifier grades every operation before the file reaches review.</p>
      <p>The practical difference: Alembic autogenerate produces a candidate revision for a human to edit. DBWarden produces a reviewable SQL artifact with rollback, classification, and impact analysis already attached. Both start from the same SQLAlchemy models. The output and the surrounding guarantees are different.</p>
    </div></section>
  </PageFrame>
}

export function SafetyPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="tool scope / safety" title={<>Database Migration Safety<br /><em>& Impact Analysis.</em></>} intro="Destructive intent is visible before the file reaches review. Operations are classified, the application is scanned for references, and risky changes stop for explicit consent. Impact analysis is one of the features that makes DBWarden meaningfully different from a simple migration runner." install="uv add dbwarden">
    <PageSection number="01" label="Safety classifier" title="Operations are classified before they run." doc="https://docs.dbwarden.org/correctness/safety-classifier/">
      <div className="why-split"><div><p>The classifier reads the migration plan before any SQL executes and grades every operation. The rule is simple: dbwarden does not silently drop data. <code className="inline-code">INFO</code> operations are expected-safe schema additions; <code className="inline-code">WARNING</code> operations need review and will not pass <code className="inline-code">check</code> without acknowledgement; <code className="inline-code">ERROR</code> operations are destructive or ambiguous and fail the check outright.</p><p><code className="inline-code">dbwarden check</code> inspects the pending plan and reports the classification. <code className="inline-code">--force</code> is an acknowledgement, not a bypass: it records that a human reviewed the classified plan and accepted the risk, which is why it should not be a default in CI. The classification is written to the <code className="inline-code">.plan.json</code> next to the generated migration, so the intent sits in the file a reviewer opens, not in a plan only the generator reads.</p></div><div><span className="comparison-label">the severity model</span><CodeBlock lang="plain">{`INFO      expected safe: create table, add nullable column\nWARNING   needs review: SET NOT NULL, type change\nERROR     blocked: DROP TABLE, DROP COLUMN, lossy engine change`}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'What makes an operation ERROR?', a: 'Anything destructive or ambiguous: dropping a table or column, renaming without explicit intent, or a lossy engine change. It fails the safety check until an operator acknowledges it explicitly.' },
        { q: 'What does the force flag do?', a: 'It records that a human reviewed the classified plan and accepted the risk. It is an acknowledgement, not a bypass, and should not be a default in CI.' },
      ]} />
    </PageSection>
    <PageSection number="02" label="Impact analysis" title="What code would a destructive change break?" doc="https://docs.dbwarden.org/cookbook/06-safety-impact/">
      <div className="why-split"><div><p>Schema changes are the highest-risk operation in most deployments: dropping a column that application code still references causes runtime errors, and changing a type can break queries. <code className="inline-code">check-impact</code> finds the code that would break before the change ships.</p><p>It scans your application code, not just the migration files, for references to objects a destructive change would remove, a column, a table, an index. The scan uses AST analysis with a grep fallback, so it catches attribute access in Python (<code className="inline-code">user.username</code>) and string matches in templates alike, and reports each hit with the access pattern, the file, and the line number, grouped by change type.</p><p>Schema safety and application safety come from the same command, so there is no separate step to forget.</p></div><div><span className="comparison-label">the scan output</span><CodeBlock>{'$ dbwarden check-impact\n\ndrop_column on users.username\n  References: 2\n    app/routes/users.py:34  attribute_access\n    app/templates/profile.jinja2:12  grep'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Does safety cover application code?', a: 'Yes, with `check-impact`. It scans Python files and templates for references to objects a destructive change would remove, so schema and application safety are reviewed together.' },
        { q: 'How does check-impact find references?', a: 'AST analysis with a grep fallback. It reports each hit with the access pattern: attribute access in Python, grep match in templates, plus the file and line number.' },
      ]} />
    </PageSection>
    <PageSection number="03" label="Safe type changes" title="The multi-step path, generated." doc="https://docs.dbwarden.org/correctness/safety-classifier/">
      <div className="why-split"><div><p>Changing a column type is where <code className="inline-code">ALTER COLUMN TYPE</code> can lock a table for the duration of a rewrite. <code className="inline-code">--safe-type-change</code> expands the change into the boring multi-step sequence instead: add a temporary column, a data migration comment, a verification step, then a swap and drop, the same sequence a careful engineer would write by hand, generated as reviewable SQL like any other migration.</p><p>Related flags tune the same operation for the backend: <code className="inline-code">--postgres-auto-using</code> emits an active <code className="inline-code">USING col::newtype</code> clause on the <code className="inline-code">ALTER COLUMN TYPE</code> instead of a commented-out line for manual review, and PostgreSQL index creation defaults to <code className="inline-code">--concurrent</code>, with <code className="inline-code">--no-concurrent</code> for migrations that run inside a transaction block.</p></div><div><span className="comparison-label">the flag</span><CodeBlock>{'$ dbwarden make-migrations "widen bio" --safe-type-change'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'What does --safe-type-change generate?', a: 'The full multi-step sequence as reviewable SQL: add the new column, backfill it from the old one, swap, then drop. Each step is a normal migration artifact with its own classification.' },
        { q: 'Where does the classification come from?', a: '`make-migrations` writes a companion `.plan.json` next to the generated SQL with the typed operations. The safety check inspects that plan before the SQL is applied.' },
      ]} />
    </PageSection>
  </PageFrame>
}

export function StatePage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="tool scope / state" title={<>Database Schema State<br /><em>and Drift Detection.</em></>} intro="Status, history, snapshots, diffs, and reverse engineering make the workflow observable: what is applied, what is pending, and whether the database actually matches the models. Schema drift is detected at generation time, before the next migration is written." install="uv add dbwarden">
    <PageSection number="01" label="Status and history" title="What is applied, and in what order." doc="https://docs.dbwarden.org/commands/status/">
      <div className="why-split"><div><p><code className="inline-code">status</code> reports the applied and pending migrations for a database, which is the before-and-after pair you read around a deploy. <code className="inline-code">history</code> lists the full versioned sequence with applied state and timestamps, the audit trail for incident analysis: which migration ran, in what order, and when.</p><p>Both work per database in a multi-database repository, or across all of them with <code className="inline-code">--all</code>. Because each database keeps its own versioned sequence, the answers are always scoped to the database you ask about.</p></div><div><span className="comparison-label">the commands</span><CodeBlock>{'$ dbwarden status\n$ dbwarden history --database primary'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'What is the difference between status and history?', a: '`status` shows the applied and pending counts for the current state of a database; `history` lists the full versioned sequence with each migration\u2019s applied state. Use `status` before and after a `migrate`, and `history` when you need the order.' },
      ]} />
    </PageSection>
    <PageSection number="02" label="Snapshots and diff" title="Reproducible diffs from committed state." doc="https://docs.dbwarden.org/correctness/deterministic-diff/">
      <div className="why-split"><div><p>After every migration, dbwarden writes a checksummed JSON snapshot of the schema to <code className="inline-code">.dbwarden/schemas/</code>. Generation diffs models against that snapshot or live state, so the same inputs produce the same SQL every time, and renames come out as renames rather than as a drop plus a create. The snapshot is what makes offline generation and deterministic diffs possible at all.</p><p><code className="inline-code">snapshot &lt;table&gt;</code> prints the DDL of a single table, a quick way to read what the database actually holds for one object. <code className="inline-code">diff</code> compares models against the database or snapshot and shows structural differences without writing anything; generation is the step that produces files, so inspection stays read-only until you ask for output.</p></div><div><span className="comparison-label">inspect the state</span><CodeBlock>{'$ dbwarden snapshot users --database primary\n$ dbwarden diff --format sql'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'What exactly is a schema snapshot?', a: 'A checksummed JSON capture of the full DDL state (tables, columns, types, indexes, constraints, enums), written to `.dbwarden/schemas/` after each applied migration. It is the baseline for deterministic diffs and offline generation.' },
        { q: 'Is diff read-only?', a: 'Yes. `diff` shows structural differences between the models and the database or snapshot without writing anything. Generation is the step that produces files.' },
      ]} />
    </PageSection>
    <PageSection number="03" label="Reverse engineering" title="An existing database back to models." doc="https://docs.dbwarden.org/commands/generate-models/">
      <div className="why-split"><div><p><code className="inline-code">generate-models</code> reads a live database and writes SQLAlchemy models, so an existing schema can be adopted instead of rebuilt from scratch. It works across all supported databases; for ClickHouse it includes engine metadata automatically when <code className="inline-code">database_type="clickhouse"</code>, and SQLite round-trips its own metadata (STRICT tables, generated columns, collations) in <code className="inline-code">SqTableMeta</code> / <code className="inline-code">SqColumnMeta</code>.</p><p><code className="inline-code">--base</code> sets the declarative base the generated models inherit from, so generated code plugs into your existing model layout instead of introducing a second one. <code className="inline-code">--tables</code> and <code className="inline-code">--exclude-tables</code> scope the output, which matters for adopting a large legacy database incrementally, and <code className="inline-code">--relationships</code> generates <code className="inline-code">relationship()</code> attributes for foreign keys. Output is one file per table by default, or a single <code className="inline-code">models.py</code> with <code className="inline-code">--single-file</code>.</p></div><div><span className="comparison-label">adopt an existing schema</span><CodeBlock>{'$ dbwarden generate-models --base app.models.Base \\\n    --tables users,posts --database primary'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Can generate-models replace a hand-written model file?', a: 'It produces one `.py` file per table by default, or a single `models.py` with `--single-file`. Use `--base` to inherit from your existing declarative base instead of generating a new one.' },
        { q: 'Can I adopt only part of a schema?', a: 'Yes. `--tables` and `--exclude-tables` scope which tables are introspected, so a large legacy database can be adopted incrementally instead of all at once.' },
      ]} />
    </PageSection>
  </PageFrame>
}

export function RepeatableMigrationsPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="tool scope / repeatable migrations" title={<>Repeatable Database<br /><em>Migrations.</em></>} intro="Not every change is a one-time schema evolution. DBWarden supports three migration classes, so database objects that outlive a single deploy stay in the same reviewable workflow." install="uv add dbwarden">
    <PageSection number="01" label="Three classes" title={<>Versioned, <code className="inline-code">runs-always</code>, <code className="inline-code">runs-on-change</code>.</>} doc="https://docs.dbwarden.org/migration-files/">
      <div className="why-split"><div><p>Versioned migrations (<code className="inline-code">NNNN_</code>) run once, in ordered version sequence: schema evolution, tables, columns, indexes, constraints. <code className="inline-code">Runs-always</code> migrations (<code className="inline-code">RA__</code>) run on every <code className="inline-code">migrate</code> execution, the class for objects that should always match the repository, views and grants. <code className="inline-code">Runs-on-change</code> migrations (<code className="inline-code">ROC__</code>) run when their content checksum changes, the class for routines and policies that should only reapply when they actually changed, functions, triggers, and policies.</p><p>At runtime, <code className="inline-code">migrate</code> builds one execution plan from file discovery plus migration metadata: pending versioned files first, then <code className="inline-code">runs-always</code> files, then <code className="inline-code">runs-on-change</code> files whose checksum differs from the last run, all under the same lock protection as the versioned sequence.</p></div><div><span className="comparison-label">the three prefixes</span><CodeBlock lang="plain">{`NNNN_  runs once, in version order\nRA__   refreshed on every migrate\nROC__  reapplied when the checksum changes`}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Which class should a function or trigger use?', a: '`Runs-on-change` (`ROC__`). The routine is reapplied only when the file content changes, so unchanged objects are left alone.' },
        { q: 'How do repeatable migrations interact with the versioned sequence?', a: '`migrate` builds the plan as pending versioned files first, then `RA__` files, then changed `ROC__` files, all under the same lock protection.' },
      ]} />
    </PageSection>
    <PageSection number="02" label="In practice" title="A view that stays current." doc="https://docs.dbwarden.org/migration-files/">
      <div className="why-split"><div><p>A <code className="inline-code">runs-always</code> migration re-creates the view on every <code className="inline-code">migrate</code>, so the definition never drifts from the repository, and a stale view cannot survive a deploy cycle. The file carries the same <code className="inline-code">-- upgrade</code> / <code className="inline-code">-- rollback</code> contract as a versioned migration, with the rollback beside the upgrade.</p><p>The ordering makes the class safe to use: because the plan applies pending versioned files before <code className="inline-code">runs-always</code> files, a view that references a column added in the same deploy picks it up in the same run, and can never be refreshed against a schema that does not yet have its objects.</p><p>You could generate the same file with <code className="inline-code">make-migrations --type ra</code> (or <code className="inline-code">roc</code>), so repeatables enter the workflow through the same generation path as versioned files instead of being hand-written in a separate system.</p></div><div><span className="comparison-label">a runs-always view</span><CodeBlock>{`-- primary__RA__refresh_active_users_view.sql\n-- upgrade\nCREATE OR REPLACE VIEW active_users AS\nSELECT id, email FROM users WHERE is_active = TRUE;\n\n-- rollback\nDROP VIEW IF EXISTS active_users;`}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Which class should a view use?', a: '`Runs-always` (`RA__`). The view is re-created on every `migrate`, so its definition is always whatever is in the repository, with no drift.' },
        { q: 'Can repeatable migrations be rolled back?', a: 'Yes. `RA__` and `ROC__` files carry the same upgrade and rollback sections as versioned migrations, with the rollback beside the upgrade.' },
      ]} />
    </PageSection>
  </PageFrame>
}

export function SeedsPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="tool scope / seeds" title={<>Database Seeds and<br /><em>Reference Data.</em></>} intro="Deterministic baseline data for local, test, and sandbox environments: code seeds and file seeds, tracked in a seed table and independent from the migration history." install="dbwarden plugin add dbwarden-seeds">
    <PageSection number="01" label="Code seeds" title="Baseline data next to your models." doc="https://docs.dbwarden.org/seeds/">
      <div className="why-split"><div><p>Code seeds live next to your models with a <code className="inline-code">Seed</code> base class and model instances. The seed declares its database, an on-conflict strategy for re-runs, and the rows to insert, so the same seed can be applied on a fresh checkout and after a rollback without duplicating rows.</p><p>Versions are auto-assigned in the <code className="inline-code">C</code> namespace (<code className="inline-code">C0001</code>, <code className="inline-code">C0002</code>, ...) from deterministic module and class ordering, so there is no manual version parameter to keep in sync with the file layout. Each version applies once until rolled back, and the seed table tracks what ran.</p><p>The on-conflict strategy decides what a re-apply does: with <code className="inline-code">__seed_on_conflict__ = "update"</code> and <code className="inline-code">__seed_conflict_columns__</code>, an existing row matching the conflict columns is updated rather than duplicated. That is what makes a code seed safe to apply on a fresh checkout and again after a partial rollback.</p></div><div><span className="comparison-label">a code seed</span><CodeBlock label="seeds.py">{`from dbwarden.seed import Seed\n\nclass CountrySeed(Seed):\n    __seed_database__ = "primary"\n    __seed_description__ = "initial countries"\n    __seed_on_conflict__ = "update"\n    __seed_conflict_columns__ = ["code"]\n\n    model = Country\n    rows = [\n        Country(code="UY", name="Uruguay"),\n        Country(code="AR", name="Argentina"),\n    ]`}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Do seeds require the plugin?', a: 'Yes. Seed management ships as the official `dbwarden-seeds` plugin: `dbwarden plugin add dbwarden-seeds`. The seed commands exist in core, but each one exits with a message until the plugin is installed.' },
        { q: 'How are code seeds versioned?', a: 'Versions are auto-assigned in the C namespace (`C0001`, `C0002`, ...) based on deterministic module and class ordering, so there is no manual version parameter to keep in sync.' },
      ]} />
    </PageSection>
    <PageSection number="02" label="File seeds and apply" title="SQL or Python in a seeds directory." doc="https://docs.dbwarden.org/seeds/">
      <div className="why-split"><div><p>File seeds are plain SQL or Python in a <code className="inline-code">seeds/</code> directory, for data that is easier to express as a script than as model rows. Both kinds are tracked in the <code className="inline-code">_dbwarden_seeds</code> table, applied with <code className="inline-code">seed apply</code>, and rolled back by removing the tracking record with <code className="inline-code">seed rollback</code>, including <code className="inline-code">--count</code> and <code className="inline-code">--to-version</code> for partial rollbacks.</p><p>Each applied seed stores a SHA-256 checksum of its file or class source. A checksum warning means the seed was modified since the last apply, so the database and the repository may disagree, and that warning is the signal to re-apply deliberately rather than silently.</p></div><div><span className="comparison-label">apply and rollback</span><CodeBlock>{'$ dbwarden seed apply --database primary\n$ dbwarden seed rollback --database primary --count 2'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'What does the checksum warning mean?', a: 'Each seed row stores a SHA-256 checksum of its file or class source. A warning means the seed was modified since the last apply, so the database and the repository may disagree.' },
        { q: 'Can seeds be rolled back?', a: 'Yes: seed rollback removes the tracking records, with `--count` or `--to-version` for a partial rollback. Each version can only be applied once until rolled back.' },
      ]} />
    </PageSection>
    <PageSection number="03" label="Seed export" title="Stateless SQL for stateless environments." doc="https://docs.dbwarden.org/seeds/">
      <div className="why-split"><div><p><code className="inline-code">seed export</code> renders code seeds to stateless runs-on-change SQL, for Dockerized deployments that should not carry application code. A container that only runs migrations should not need your models and their imports just to seed a few reference rows.</p><p><code className="inline-code">auto_apply_seeds</code> runs pending seeds after every <code className="inline-code">migrate</code>, so a fresh environment comes up fully seeded in one command, with the seed history visible in the same status flow as the migration history.</p></div><div><span className="comparison-label">the export</span><CodeBlock>{'$ dbwarden seed export --database primary'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Why use seed export instead of applying code seeds?', a: 'Code seeds need your application environment to execute. `seed export` renders them to stateless `runs-on-change` SQL, so containers do not need the application code just to seed data.' },
      ]} />
    </PageSection>
  </PageFrame>
}

export function ObservabilityPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="tool scope / observability" title={<>Database Migration<br /><em>Observability.</em></>} intro="The workflow is observable: Prometheus metrics from `migrate` and `seed` commands, newline-delimited JSON for log pipelines, and `trace-level` SQL when you need to see every statement." install="uv add dbwarden">
    <PageSection number="01" label="Metrics" title="Prometheus counters, gauges, histograms." doc="https://docs.dbwarden.org/observability/">
      <div className="why-split"><div><p>Set <code className="inline-code">DBWARDEN_METRICS=true</code> and <code className="inline-code">migrate</code> and <code className="inline-code">seed apply</code> record counters, gauges, and histograms: migrations applied and migration errors as counters, migration duration as a histogram, and schema version, seed version, and pending migrations as gauges, all labeled by database. The metric types match what each question needs: a counter for how many times a migration ran, a gauge for the current schema version, a histogram for how long applies take.</p><p>The FastAPI plugin exposes them at <code className="inline-code">/metrics</code> via the <code className="inline-code">MetricsRouter</code> and <code className="inline-code">MetricsMiddleware</code>, so one scrape target covers both the application and the migration commands it runs. The dependency is optional: <code className="inline-code">uv add "dbwarden[metrics]"</code> installs <code className="inline-code">prometheus-client</code>, and without it every metric function is a safe no-op.</p></div><div><span className="comparison-label">enable metrics</span><CodeBlock>{'$ DBWARDEN_METRICS=true dbwarden migrate'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Is the metrics dependency optional?', a: 'Yes: `uv add "dbwarden[metrics]"` installs `prometheus-client`. When it is not installed or `DBWARDEN_METRICS` is unset, all metric functions are safe no-ops.' },
        { q: 'Which metrics does migrate record?', a: 'Counters for migrations applied and migration errors, a histogram for migration duration, and gauges for schema version, seed version, and pending migrations, all labeled by database.' },
        { q: 'Why does /metrics return 404?', a: 'The FastAPI endpoint is only active when `prometheus-client` is installed and `DBWARDEN_METRICS=true` is set. Disabled otherwise by design.' },
      ]} />
    </PageSection>
    <PageSection number="02" label="Logs" title={<>JSON lines, or <code className="inline-code">trace-level</code> SQL.</>} doc="https://docs.dbwarden.org/observability/">
      <div className="why-split"><div><p><code className="inline-code">DBWARDEN_LOG_JSON</code> switches to newline-delimited JSON for ELK, Loki, or Datadog, one object per line, ready for structured parsing instead of text scraping. The global <code className="inline-code">--json</code> flag does the same for a single run and also switches display commands to JSON output, while the environment variable makes JSON the default for the whole environment.</p><p>When you need to see exactly what ran against the database, <code className="inline-code">--debug-level trace</code> logs every SQL statement as it executes during migrate, rollback, and downgrade, and <code className="inline-code">--perf</code> adds per-statement timing. Trace is below debug in the level ordering, so it is explicitly opt-in: normal runs stay quiet, and the full statement log is there when an incident needs it.</p></div><div><span className="comparison-label">json or trace</span><CodeBlock>{'$ DBWARDEN_LOG_JSON=true dbwarden migrate --debug-level trace'}</CodeBlock></div></div>
      <Faq variant="inline" items={[
        { q: 'Is --json the same as DBWARDEN_LOG_JSON?', a: 'The global `--json` flag switches log output to JSON for that run and also switches display commands to JSON output. `DBWARDEN_LOG_JSON` makes JSON the default for the environment.' },
        { q: 'What does trace level add over debug?', a: 'Trace (level 5, below debug) logs every SQL statement as it executes during `migrate`, `rollback`, and `downgrade`. `--perf` adds each statement\u2019s duration.' },
      ]} />
    </PageSection>
  </PageFrame>
}
