import './page-styles.css'
import { PageFrame, PageSection, Faq } from './pages.jsx'
import { CodeBlock } from './code.jsx'

export function MigrateFromAlembicPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="migrate from alembic" title={<>Migrate from Alembic<br /><em>to dbwarden.</em></>} intro="Already using Alembic? Start here. Alembic keeps schema truth in a chain of revision scripts; dbwarden keeps it in the models and derives plain SQL migrations from them. Your models stay exactly where they are and your database is never rebuilt; you are replacing the migration workflow, not the schema. Alembic history stays in git, which is where old revisions belong.">
    <PageSection number="01" label="Concept map" title="Every Alembic concept has a dbwarden counterpart." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><div className="databases-table-wrap"><table className="databases-table"><thead><tr><th>Alembic</th><th>dbwarden</th></tr></thead><tbody><tr><th>alembic.ini + env.py</th><td>dbwarden.py config file</td></tr><tr><th>Revision script (.py)</th><td>Migration file (.sql) with upgrade / rollback sections</td></tr><tr><th>Revision chain as source of truth</th><td>SQLAlchemy models as source of truth</td></tr><tr><th>alembic revision --autogenerate</th><td>dbwarden make-migrations "description"</td></tr><tr><th>alembic upgrade head</th><td>dbwarden migrate</td></tr><tr><th>alembic downgrade -1</th><td>dbwarden rollback</td></tr><tr><th>alembic stamp &lt;rev&gt;</th><td>dbwarden migrate --baseline</td></tr><tr><th>alembic current</th><td>dbwarden status</td></tr><tr><th>alembic history</th><td>dbwarden history</td></tr><tr><th>alembic upgrade head --sql</th><td>export-models + make-migrations --offline</td></tr></tbody></table></div><p>Two Alembic features have no direct equivalent, and it is worth knowing before you start: Python data migrations (dbwarden manual migrations are SQL) and revision branching and merging (dbwarden uses a linear versioned sequence per database).</p></PageSection>
    <PageSection number="02" label="The shape of the change" title="Before and after." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><div className="why-split"><div><p>In Alembic, a schema change is a revision script: a Python module with a revision id, a <code className="inline-code">down_revision</code> pointer, and upgrade and downgrade functions that call <code className="inline-code">op.*</code> builders. The chain of these scripts becomes the schema's effective definition.</p><p>In dbwarden the same change starts as a model edit, and the migration is the SQL derived from it, upgrade and rollback in the same file, generated from the same diff. Both sides below describe the same change: add a nullable <code className="inline-code">bio</code> column to <code className="inline-code">users</code>.</p></div><div><span className="comparison-label muted">alembic revision</span><CodeBlock label="revision.py">{`revision = "ae1027a6acf"\ndown_revision = "1975ea83b712"\n\ndef upgrade():\n    op.add_column("users", sa.Column("bio", sa.Text()))\n\ndef downgrade():\n    op.drop_column("users", "bio")`}</CodeBlock><span className="comparison-label">dbwarden model + artifact</span><CodeBlock label="models.py">{`class User(Base):\n    bio = Column(Text, nullable=True)\n\n-- upgrade\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- rollback\nALTER TABLE users DROP COLUMN bio;`}</CodeBlock></div></div></PageSection>
    <PageSection number="03" label="The steps" title="Six steps, none of them destructive." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><div className="fit-grid"><div><strong>01: Install and configure</strong><p><code className="inline-code">uv add dbwarden</code>, create <code className="inline-code">dbwarden.py</code>. This replaces alembic.ini and env.py. Model discovery is automatic; use <code className="inline-code">model_paths</code> to constrain it.</p></div><div><strong>02: Generate the baseline</strong><p><code className="inline-code">make-migrations "baseline from alembic"</code> emits the full schema from your models. If the diff looks wrong, your models and database disagree; better to learn that now.</p></div><div><strong>03: Baseline the database</strong><p><code className="inline-code">migrate --baseline</code> records the migration as applied without running it. This is the stamp equivalent.</p></div><div><strong>04: Verify convergence</strong><p><code className="inline-code">status</code>, <code className="inline-code">check</code>, and <code className="inline-code">diff</code> must all be clean. If diff reports no differences, dbwarden and reality agree.</p></div><div><strong>05: Offline CI (optional)</strong><p><code className="inline-code">export-models</code>, commit the state file, and drop the database service: <code className="inline-code">make-migrations --offline</code> from then on.</p></div><div><strong>06: Retire Alembic</strong><p>Remove alembic.ini, env.py, and versions/ from the active workflow. Replace <code className="inline-code">alembic upgrade head</code> with <code className="inline-code">dbwarden migrate</code>. The alembic_version table is inert.</p></div></div><div className="why-split"><div><p>Both tools can coexist during a transition period; they track state in separate tables. Generate the same change with both and compare the SQL until you are confident. Keep the overlap short.</p></div><div><span className="comparison-label">the whole sequence</span><CodeBlock label="terminal">{`$ dbwarden init\n$ dbwarden make-migrations "baseline from alembic"\n$ dbwarden migrate --baseline\n$ dbwarden status\n$ dbwarden diff`}</CodeBlock></div></div></PageSection>
    <PageSection number="04" label="Workflow changes" title="What your team will notice." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><div className="why-split"><div><p>The daily changes are mostly removals: no revision ids to invent, no <code className="inline-code">down_revision</code> chains to keep straight, no hand-written downgrade stubs. Four things stand out to a team coming from Alembic.</p><ul><li><strong>Renames are explicit.</strong> <code className="inline-code">--rename users.name:full_name</code> and <code className="inline-code">--rename-table order:orders</code>. A rename never silently becomes a drop-and-create.</li><li><strong>Rollback is a contract.</strong> Executable rollback sits beside every upgrade; placeholder rollback is refused.</li><li><strong>Table metadata moves into class Meta.</strong> Comments, advanced indexes, and backend options live on the model.</li><li><strong>Destructive changes can be checked first.</strong> <code className="inline-code">check-impact</code> reports which code still references a column or table you are about to drop.</li></ul></div><div><span className="comparison-label">the flags</span><CodeBlock label="terminal">{`$ dbwarden make-migrations "rename name" --rename users.name:full_name\n$ dbwarden make-migrations "pluralize" --rename-table order:orders\n\n$ dbwarden check-impact 0002 --database primary`}</CodeBlock></div></div></PageSection>
    <Faq items={[
      { q: 'What happens to the existing Alembic history?', a: 'It stays in git, which is where old revisions belong. `make-migrations "baseline from alembic"` emits the full current schema from your models, and `migrate --baseline` records it as applied without running any DDL. The alembic_version table is left inert; nothing is rebuilt or dropped.' },
      { q: 'Can dbwarden and Alembic run side by side during the transition?', a: 'Yes. They track state in separate tables, so both tools can coexist. A common approach is generating the same change with both and comparing the SQL until you are confident; keep the overlap short.' },
      { q: 'Do the models have to change?', a: 'No. Your models stay exactly where they are; dbwarden reads them as the schema authority. Comments, advanced indexes, and backend options can move into `class Meta`, but that is optional and can happen incrementally.' },
      { q: 'What is lost by switching?', a: 'Python data migrations (dbwarden manual migrations are SQL) and revision branching and merging (dbwarden uses a linear versioned sequence per database). If either is central to your workflow, stay with Alembic.' },
      { q: 'Is the database ever rebuilt?', a: 'No. You are replacing the migration workflow, not the schema. `migrate --baseline` records the current schema as already applied without executing DDL, and `generate-models` can adopt an existing database into models when they were never written.' },
    ]} />
    <section className="fit-section"><div className="section-label">/ when to stay</div><div className="fit-grid"><div><strong>Stay with Alembic when</strong><p>Python data migrations are central to your workflow, you rely on branching and merging revision graphs, or you want imperative control over every step.</p></div><div><strong>Switch when</strong><p>Most of your migrations are pure schema changes and you want models as the source of truth with SQL you review in the pull request.</p></div></div></section>
    <section className="article-links"><div className="section-label">/ keep reading</div><div><a href="/alembic-alternative">New to dbwarden? See why it differs from Alembic <span>↗</span></a><a href="/compare/alembic">dbwarden vs Alembic <span>↗</span></a><a href="https://docs.dbwarden.org/getting-started/migrating-from-alembic/" target="_blank" rel="noreferrer">The full migration guide <span>↗</span></a></div></section>
  </PageFrame>
}
