import { PageFrame, PageSection, CodeBlock } from './pages.jsx'

export function MigrateFromAlembicPage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="migrate from alembic" title={<>Keep the models.<br /><em>Retire the revision chain.</em></>} intro="Alembic keeps schema truth in a chain of revision scripts; dbwarden keeps it in the models and derives plain SQL migrations from them. Your models stay exactly where they are and your database is never rebuilt; you are replacing the migration workflow, not the schema. Alembic history stays in git, which is where old revisions belong.">
    <PageSection number="01" label="Concept map" title="Every Alembic concept has a dbwarden counterpart." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><table className="databases-table"><thead><tr><th>Alembic</th><th>dbwarden</th></tr></thead><tbody><tr><th>alembic.ini + env.py</th><td>dbwarden.py config file</td></tr><tr><th>Revision script (.py)</th><td>Migration file (.sql) with upgrade / rollback sections</td></tr><tr><th>Revision chain as source of truth</th><td>SQLAlchemy models as source of truth</td></tr><tr><th>alembic revision --autogenerate</th><td>dbwarden make-migrations "description"</td></tr><tr><th>alembic upgrade head</th><td>dbwarden migrate</td></tr><tr><th>alembic downgrade -1</th><td>dbwarden rollback</td></tr><tr><th>alembic stamp &lt;rev&gt;</th><td>dbwarden migrate --baseline</td></tr><tr><th>alembic current</th><td>dbwarden status</td></tr><tr><th>alembic history</th><td>dbwarden history</td></tr><tr><th>alembic upgrade head --sql</th><td>export-models + make-migrations --offline</td></tr></tbody></table><p>Two Alembic features have no direct equivalent, and it is worth knowing before you start: Python data migrations (dbwarden manual migrations are SQL) and revision branching and merging (dbwarden uses a linear versioned sequence per database).</p></PageSection>
    <PageSection number="02" label="The shape of the change" title="Before and after." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><div className="comparison-code-grid"><div><span className="comparison-label muted">Alembic revision</span><CodeBlock>{`revision = "ae1027a6acf"
down_revision = "1975ea83b712"

def upgrade():
    op.add_column("users", sa.Column("bio", sa.Text()))

def downgrade():
    op.drop_column("users", "bio")`}</CodeBlock></div><div><span className="comparison-label">dbwarden model + artifact</span><CodeBlock>{`class User(Base):
    bio = Column(Text, nullable=True)

-- upgrade
ALTER TABLE users ADD COLUMN bio TEXT;

-- rollback
ALTER TABLE users DROP COLUMN bio;`}</CodeBlock></div></div></PageSection>
    <PageSection number="03" label="The steps" title="Six steps, none of them destructive." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><div className="fit-grid"><div><strong>01: Install and configure</strong><p><code className="inline-code">uv add dbwarden</code>, create <code className="inline-code">dbwarden.py</code>. This replaces alembic.ini and env.py. Model discovery is automatic; use <code className="inline-code">model_paths</code> to constrain it.</p></div><div><strong>02: Generate the baseline</strong><p><code className="inline-code">make-migrations "baseline from alembic"</code> emits the full schema from your models. If the diff looks wrong, your models and database disagree; better to learn that now.</p></div><div><strong>03: Baseline the database</strong><p><code className="inline-code">migrate --baseline</code> records the migration as applied without running it. This is the stamp equivalent.</p></div><div><strong>04: Verify convergence</strong><p><code className="inline-code">status</code>, <code className="inline-code">check</code>, and <code className="inline-code">diff</code> must all be clean. If diff reports no differences, dbwarden and reality agree.</p></div><div><strong>05: Offline CI (optional)</strong><p><code className="inline-code">export-models</code>, commit the state file, and drop the database service: <code className="inline-code">make-migrations --offline</code> from then on.</p></div><div><strong>06: Retire Alembic</strong><p>Remove alembic.ini, env.py, and versions/ from the active workflow. Replace <code className="inline-code">alembic upgrade head</code> with <code className="inline-code">dbwarden migrate</code>. The alembic_version table is inert.</p></div></div><CodeBlock>{`$ dbwarden init
$ dbwarden make-migrations "baseline from alembic"
$ dbwarden migrate --baseline
$ dbwarden status
$ dbwarden diff`}</CodeBlock><p>Both tools can coexist during a transition period; they track state in separate tables. Generate the same change with both and compare the SQL until you are confident. Keep the overlap short.</p></PageSection>
    <PageSection number="04" label="Workflow changes" title="What your team will notice." doc="https://docs.dbwarden.org/getting-started/migrating-from-alembic/"><ul><li><strong>Renames are explicit.</strong> <code className="inline-code">--rename users.name:full_name</code> and <code className="inline-code">--rename-table order:orders</code>. A rename never silently becomes a drop-and-create.</li><li><strong>Rollback is a contract.</strong> Executable rollback sits beside every upgrade; placeholder rollback is refused.</li><li><strong>Table metadata moves into class Meta.</strong> Comments, advanced indexes, and backend options live on the model.</li><li><strong>Destructive changes can be checked first.</strong> <code className="inline-code">check-impact</code> reports which code still references a column or table you are about to drop.</li></ul></PageSection>
    <section className="fit-section"><div className="section-label">/ when to stay</div><div className="fit-grid"><div><strong>Stay with Alembic when</strong><p>Python data migrations are central to your workflow, you rely on branching and merging revision graphs, or you want imperative control over every step.</p></div><div><strong>Switch when</strong><p>Most of your migrations are pure schema changes and you want models as the source of truth with SQL you review in the pull request.</p></div></div></section>
    <section className="article-links"><div className="section-label">/ keep reading</div><div><a href="/compare/alembic">dbwarden vs Alembic <span>↗</span></a><a href="https://docs.dbwarden.org/getting-started/migrating-from-alembic/" target="_blank" rel="noreferrer">The full migration guide <span>↗</span></a></div></section>
  </PageFrame>
}
