import './page-styles.css'
import { PageFrame, PageSection, Faq } from './pages.jsx'
import { CodeBlock } from './code.jsx'

export function WlitePage({ dark, toggleTheme }) {
  return <PageFrame dark={dark} toggleTheme={toggleTheme} eyebrow="wlite + libwlite" title={<>A Small Schema Engine<br /><em>for Every Runtime.</em></>} intro="wlite and libwlite are the lower-level pieces of the dbwarden ecosystem: a compact schema language, planner, and migration engine that can run without Python." install="git clone https://github.com/dbwarden-org/wlite">
    <PageSection number="01" label="The pair" title="One engine, two ways to use it." doc="https://github.com/dbwarden-org/wlite">
      <div className="why-split"><div><p><code className="inline-code">libwlite</code> is the embeddable C library. It parses schema definitions, introspects database state, computes diffs, builds migration plans, and emits SQL without requiring an application framework.</p><p><code className="inline-code">wlite</code> is the user-facing CLI built on that engine. It adds a practical workflow for <code className="inline-code">migrate</code>, <code className="inline-code">diff</code>, <code className="inline-code">plan</code>, <code className="inline-code">compile</code>, snapshots, and schema hashes, plus C++, Python, and Rust bindings.</p><p>They are related to dbwarden, not a dbwarden plugin. dbwarden is the model-native SQLAlchemy workflow; wlite is the portable schema engine underneath the language boundary.</p></div><div><span className="comparison-label">the workflow</span><CodeBlock lang="plain">{'schema definition -> parse -> introspect -> diff -> plan -> migrate'}</CodeBlock></div></div>
    </PageSection>
    <PageSection number="02" label="libwlite" title="The portable core." doc="https://github.com/dbwarden-org/libwlite">
      <div className="why-split"><div><p>The C library keeps the core operations small and composable. Applications can embed parsing, schema introspection, planning, and SQL generation directly, then keep their own runtime, deployment model, and language bindings around it.</p><p>It is designed for predictable tooling rather than a large framework: schema state can be snapshotted and hashed, changes become typed plan operations, and the generated SQL remains inspectable before it is applied.</p></div><div><span className="comparison-label">library surface</span><CodeBlock lang="plain">{'parse | introspect | snapshot | diff | plan | emit'}</CodeBlock><a className="text-link" href="https://github.com/dbwarden-org/libwlite" target="_blank" rel="noreferrer">Explore libwlite on GitHub <span>↗</span></a></div></div>
    </PageSection>
    <PageSection number="03" label="wlite" title="A CLI for the same engine." doc="https://github.com/dbwarden-org/wlite">
      <div className="why-split"><div><p>Use the CLI when you want the engine’s workflow from a shell, CI job, or deployment image. Compile a schema, inspect a plan, compare snapshots, or run a migration without bringing an application framework into the process.</p><p>The bindings expose the same engine to C++, Python, and Rust programs. That makes wlite useful at the edge of a system too: a service can own schema changes in its native runtime while sharing the same state and migration semantics.</p></div><div><span className="comparison-label">inspect before apply</span><CodeBlock lang="shell">{'$ wlite compile schema.wl --output schema.sql\n$ wlite snapshot app.db --output state.json\n$ wlite diff state.json schema.wl\n$ wlite plan schema.wl\n$ wlite migrate app.db schema.wl'}</CodeBlock><a className="text-link" href="https://github.com/dbwarden-org/wlite/tree/master/docs" target="_blank" rel="noreferrer">Read the wlite documentation <span>↗</span></a></div></div>
    </PageSection>
    <section className="fit-section"><div className="section-label">/ choose the layer</div><div className="fit-grid"><div><strong>Choose libwlite</strong><p>You are embedding schema and migration behavior into a native application or building another binding.</p><a className="text-link" href="https://github.com/dbwarden-org/libwlite" target="_blank" rel="noreferrer">C library repository <span>↗</span></a></div><div><strong>Choose wlite</strong><p>You want the ready-to-run CLI, portable bindings, and a compact workflow for compile, diff, plan, snapshot, and migrate.</p><a className="text-link" href="https://github.com/dbwarden-org/wlite" target="_blank" rel="noreferrer">CLI and bindings repository <span>↗</span></a></div><div><strong>Choose dbwarden</strong><p>You use SQLAlchemy models as the source of truth and want generated SQL migrations with database-aware metadata.</p><a className="text-link" href="https://github.com/dbwarden-org/dbwarden" target="_blank" rel="noreferrer">dbwarden repository <span>↗</span></a></div></div></section>
    <Faq items={[
      { q: 'Is wlite a dbwarden plugin?', a: 'No. wlite and libwlite are related projects in the ecosystem, not plugins. dbwarden provides the SQLAlchemy and Python workflow; wlite provides a portable lower-level engine and CLI.' },
      { q: 'What languages does wlite support?', a: 'The engine is written in C, with C++, Python, and Rust bindings in the wlite repository.' },
      { q: 'Can wlite and dbwarden be used together?', a: 'Yes, where their artifacts or responsibilities meet. Use dbwarden for model-driven SQLAlchemy migrations and wlite when a portable schema engine, native binding, or framework-independent migration tool fits better.' },
    ]} />
  </PageFrame>
}
